import { randomUUID } from 'node:crypto';
import { Injectable, Scope } from 'graphql-modules';
import type { PoolClient } from 'pg';
import { sql } from '@pgtyped/runtime';
import { DocumentType } from '../../../shared/enums.js';
import { hashStringToInt } from '../../../shared/helpers/index.js';
import { CloudinaryProvider } from '../../app-providers/cloudinary.js';
import { DBProvider } from '../../app-providers/db.provider.js';
import { IngestOutcome, IngestReasonCode } from '../contracts.js';
import { computeDedupFingerprint } from '../helpers/email-ingestion-dedup.helper.js';
import { withTenantContext } from '../helpers/email-ingestion-tenant-context.helper.js';
import { EmailIngestionControlProvider } from './email-ingestion-control.provider.js';

// ---------------------------------------------------------------------------
// Inline query types (normally generated by `yarn generate:sql`)
// ---------------------------------------------------------------------------

interface ICheckIdempotencyForIngestQuery {
  params: { idempotencyKey: string; ownerId: string };
  result: {
    id: string;
    idempotency_key: string;
    owner_id: string;
    outcome: string;
    ingest_id: string | null;
    audit_id: string;
    created_at: Date;
  };
}

interface IInsertIdempotencyForIngestQuery {
  params: {
    idempotencyKey: string;
    ownerId: string;
    outcome: string;
    ingestId: string | null;
    auditId: string;
  };
  result: {
    id: string;
    idempotency_key: string;
    owner_id: string;
    outcome: string;
    ingest_id: string | null;
    audit_id: string;
    created_at: Date;
  };
}

interface ICheckDedupForIngestQuery {
  params: { ownerId: string; fingerprint: string };
  result: {
    id: string;
    owner_id: string;
    fingerprint: string;
    outcome: string;
    ingest_id: string | null;
    correlation_id: string | null;
    created_at: Date;
  };
}

interface IInsertDedupForIngestQuery {
  params: {
    ownerId: string;
    fingerprint: string;
    outcome: string;
    ingestId: string | null;
    correlationId: string | null;
  };
  result: {
    id: string;
    owner_id: string;
    fingerprint: string;
    outcome: string;
    ingest_id: string | null;
    correlation_id: string | null;
    created_at: Date;
  };
}

interface IInsertQuarantineForIngestQuery {
  params: {
    reasonCode: string;
    tenantCandidate: string;
    messageId: string | null;
    rawMessageHash: string | null;
    correlationId: string;
  };
  result: { id: string };
}

// Document persistence (Workstream D). The gateway control-plane caller has no
// auth session, so the auth-coupled DocumentsProvider / ChargesProvider /
// getDocumentFromFile cannot be used here; these inline queries run on the
// tenant-pinned client (cf. the idempotency/dedup/quarantine inserts above), so
// the documents/charges `tenant_isolation` RLS WITH CHECK (owner_id =
// get_current_business_id()) is satisfied by the pinned tenant.
interface ICheckDocumentByHashForIngestQuery {
  params: { ownerId: string; fileHash: string };
  result: { id: string };
}

interface IInsertChargeForIngestQuery {
  params: { ownerId: string; userDescription: string; accountantStatus: string };
  result: { id: string };
}

interface IInsertDocumentForIngestQuery {
  params: {
    ownerId: string;
    chargeId: string;
    creditorId: string | null;
    documentType: string;
    fileUrl: string;
    imageUrl: string;
    fileHash: string;
  };
  result: { id: string };
}

// ---------------------------------------------------------------------------
// SQL queries
// ---------------------------------------------------------------------------

const checkIdempotencyKey = sql<ICheckIdempotencyForIngestQuery>`
  SELECT id, idempotency_key, owner_id, outcome, ingest_id, audit_id, created_at
    FROM accounter_schema.email_ingestion_idempotency_keys
   WHERE idempotency_key = $idempotencyKey
     AND owner_id = $ownerId
   LIMIT 1
`;

const insertIdempotencyKey = sql<IInsertIdempotencyForIngestQuery>`
  INSERT INTO accounter_schema.email_ingestion_idempotency_keys
    (idempotency_key, owner_id, outcome, ingest_id, audit_id)
  VALUES ($idempotencyKey, $ownerId, $outcome, $ingestId, $auditId)
  ON CONFLICT (idempotency_key, owner_id) DO NOTHING
  RETURNING id, idempotency_key, owner_id, outcome, ingest_id, audit_id, created_at
`;

const checkDedupFingerprint = sql<ICheckDedupForIngestQuery>`
  SELECT id, owner_id, fingerprint, outcome, ingest_id, correlation_id, created_at
    FROM accounter_schema.email_ingestion_dedup_fingerprints
   WHERE owner_id = $ownerId
     AND fingerprint = $fingerprint
   LIMIT 1
`;

const insertDedupFingerprint = sql<IInsertDedupForIngestQuery>`
  INSERT INTO accounter_schema.email_ingestion_dedup_fingerprints
    (owner_id, fingerprint, outcome, ingest_id, correlation_id)
  VALUES ($ownerId, $fingerprint, $outcome, $ingestId, $correlationId)
  ON CONFLICT (owner_id, fingerprint) DO NOTHING
  RETURNING id, owner_id, fingerprint, outcome, ingest_id, correlation_id, created_at
`;

const insertQuarantine = sql<IInsertQuarantineForIngestQuery>`
  INSERT INTO accounter_schema.email_ingestion_quarantine
    (reason_code, tenant_candidate, message_id, raw_message_hash, correlation_id)
  VALUES ($reasonCode, $tenantCandidate, $messageId, $rawMessageHash, $correlationId)
  RETURNING id
`;

const checkDocumentByHash = sql<ICheckDocumentByHashForIngestQuery>`
  SELECT id
    FROM accounter_schema.documents
   WHERE owner_id = $ownerId
     AND file_hash = $fileHash
   LIMIT 1
`;

const insertIngestCharge = sql<IInsertChargeForIngestQuery>`
  INSERT INTO accounter_schema.charges
    (owner_id, type, accountant_status, user_description, tax_category_id, optional_vat, documents_optional_flag, is_property)
  VALUES ($ownerId, NULL, $accountantStatus, $userDescription, NULL, FALSE, FALSE, FALSE)
  RETURNING id
`;

const insertIngestDocument = sql<IInsertDocumentForIngestQuery>`
  INSERT INTO accounter_schema.documents
    (owner_id, charge_id, type, file_url, image_url, file_hash, creditor_id)
  VALUES ($ownerId, $chargeId, $documentType, $fileUrl, $imageUrl, $fileHash, $creditorId)
  RETURNING id
`;

// ---------------------------------------------------------------------------
// Public input / output types
// ---------------------------------------------------------------------------

export type IngestInput = {
  grantJti: string;
  idempotencyKey: string;
  tenantId: string;
  messageId: string;
  rawMessageHash: string;
  correlationId?: string;
  extractedDocuments: Array<{
    hash: string;
    sizeBytes: number;
    mimeType: string;
    filename?: string | null;
    /** Base64-encoded document bytes (inline transport); omitted = metadata only. */
    content?: string | null;
  }>;
};

/** An uploaded document ready to be inserted (bytes already in Cloudinary). */
type PreparedDocument = { fileUrl: string; imageUrl: string; fileHash: string };

export type IngestResult =
  | { outcome: typeof IngestOutcome.INSERTED; ingestId: string; auditId: string }
  | {
      outcome: typeof IngestOutcome.DUPLICATE;
      existingIngestId: string | null;
      auditId: string;
    }
  | { outcome: typeof IngestOutcome.QUARANTINED; auditId: string; reasonCode: string }
  | { outcome: typeof IngestOutcome.REJECTED; reasonCode: string };

// ---------------------------------------------------------------------------
// Provider
// ---------------------------------------------------------------------------

/**
 * Orchestrates the v2 ingest flow for gateway-initiated ingestion.
 *
 * The caller presents a gateway_control_plane auth token with an empty
 * businessId, so TenantAwareDBClient (which derives the tenant from the auth
 * session) cannot be used here — the authoritative tenant comes from the
 * single-use, cryptographically-validated grant instead. To still get RLS as a
 * second defense layer, all tenant-bound reads/writes run inside one
 * transaction whose `app.current_business_id` is pinned to the grant tenant
 * (see {@link withTenantContext}); the `tenant_isolation` WITH CHECK policies
 * on the idempotency/dedup/quarantine tables then enforce
 * `owner_id = tenantId` on top of the explicit owner_id filters in each query.
 *
 * Flow: grant validation → idempotency check → dedup check → quarantine or insert.
 */
@Injectable({
  scope: Scope.Singleton,
  global: true,
})
export class EmailIngestionIngestProvider {
  constructor(
    private dbProvider: DBProvider,
    private controlProvider: EmailIngestionControlProvider,
    private cloudinaryProvider: CloudinaryProvider,
  ) {}

  async performIngest(input: IngestInput): Promise<IngestResult> {
    const {
      grantJti,
      idempotencyKey,
      tenantId,
      messageId,
      rawMessageHash,
      correlationId,
      extractedDocuments,
    } = input;

    // 1. Validate and atomically consume the grant (control-plane, pre-tenant).
    const grantResult = await this.controlProvider.validateAndConsumeGrant({
      jti: grantJti,
      tenantId,
      messageId,
      rawMessageHash,
    });

    if (!grantResult.valid) {
      return { outcome: IngestOutcome.REJECTED, reasonCode: grantResult.reason };
    }

    const corrId = correlationId ?? randomUUID();
    const fingerprint = computeDedupFingerprint(tenantId, rawMessageHash);

    // Prepare documents (hash dedup read + Cloudinary upload) BEFORE the write
    // transaction, so the network I/O never holds a pooled connection / open
    // transaction while uploading. The dedup short-circuits re-deliveries (their
    // documents already exist) so they don't re-upload.
    const preparedDocuments = await this.prepareDocuments(tenantId, extractedDocuments);

    // 2–5. All tenant-bound work runs under the grant tenant's RLS context.
    return withTenantContext(this.dbProvider.pool, tenantId, async client => {
      // 2. Idempotency check — return prior outcome if this key was already processed.
      const idemRows = await checkIdempotencyKey.run({ idempotencyKey, ownerId: tenantId }, client);
      if (idemRows.length > 0) {
        const r = idemRows[0];
        return {
          outcome: IngestOutcome.DUPLICATE,
          existingIngestId: r.ingest_id,
          auditId: r.audit_id,
        };
      }

      // 3. Dedup fingerprint check — detect identical content re-delivery.
      const dedupRows = await checkDedupFingerprint.run({ ownerId: tenantId, fingerprint }, client);
      if (dedupRows.length > 0) {
        const r = dedupRows[0];
        return {
          outcome: IngestOutcome.DUPLICATE,
          existingIngestId: r.ingest_id,
          auditId: randomUUID(),
        };
      }

      // 4. Quarantine if no documents were extracted.
      if (extractedDocuments.length === 0) {
        await insertQuarantine.run(
          {
            reasonCode: IngestReasonCode.NO_DOCUMENTS,
            tenantCandidate: tenantId,
            messageId,
            rawMessageHash,
            correlationId: corrId,
          },
          client,
        );

        const auditId = randomUUID();
        await this.persistIdempotencyAndDedup({
          idempotencyKey,
          tenantId,
          fingerprint,
          outcome: IngestOutcome.QUARANTINED,
          ingestId: null,
          auditId,
          correlationId: corrId,
          client,
        });

        return {
          outcome: IngestOutcome.QUARANTINED,
          auditId,
          reasonCode: IngestReasonCode.NO_DOCUMENTS,
        };
      }

      // 5. Happy path: insert the prepared documents (charge + documents) under
      // the recognized business bound in the grant — no network I/O here, the
      // bytes were already uploaded outside this transaction — then record the
      // ingest. The created charge id doubles as the ingest id; with nothing new
      // to persist (metadata-only, or all duplicates) a synthetic id is used.
      const chargeId =
        preparedDocuments.length > 0
          ? await this.insertPreparedDocuments(client, {
              tenantId,
              businessId: grantResult.grant.businessId,
              messageId,
              preparedDocuments,
            })
          : null;

      const ingestId = chargeId ?? randomUUID();
      const auditId = randomUUID();

      const idemResult = await this.persistIdempotencyAndDedup({
        idempotencyKey,
        tenantId,
        fingerprint,
        outcome: IngestOutcome.INSERTED,
        ingestId,
        auditId,
        correlationId: corrId,
        client,
      });

      return {
        outcome: IngestOutcome.INSERTED,
        ingestId: idemResult.ingestId ?? ingestId,
        auditId: idemResult.auditId,
      };
    });
  }

  /**
   * Prepare the inline document bytes (Option B transport) for persistence
   * WITHOUT holding the write transaction open: dedup new documents by hash (a
   * short read context) and upload the new ones to Cloudinary in parallel,
   * outside any transaction. Keeping the network I/O off the main ingest
   * transaction avoids holding a pooled connection during slow/large uploads.
   *
   * The hash matches the legacy `hashStringToInt(file.text())` scheme so the
   * dedup is consistent with documents inserted via `insertEmailDocuments`;
   * re-deliveries short-circuit here (their documents already exist) and never
   * re-upload. Metadata-only entries (no inline bytes) yield an empty result.
   */
  private async prepareDocuments(
    tenantId: string,
    documents: IngestInput['extractedDocuments'],
  ): Promise<PreparedDocument[]> {
    type DocWithContent = (typeof documents)[number] & { content: string };
    const withContent = documents.filter(
      (doc): doc is DocWithContent => typeof doc.content === 'string' && doc.content.length > 0,
    );
    if (withContent.length === 0) {
      return [];
    }

    const candidates = withContent.map(doc => ({
      doc,
      fileHash: hashStringToInt(Buffer.from(doc.content, 'base64').toString('utf8')).toString(),
    }));

    // Find the documents new to this tenant under its RLS context (a short read,
    // no network I/O held in a long-lived transaction).
    const newCandidates = await withTenantContext(this.dbProvider.pool, tenantId, async client => {
      const fresh: typeof candidates = [];
      for (const candidate of candidates) {
        const existing = await checkDocumentByHash.run(
          { ownerId: tenantId, fileHash: candidate.fileHash },
          client,
        );
        if (existing.length === 0) {
          fresh.push(candidate);
        }
      }
      return fresh;
    });

    // Upload the new documents in parallel, outside any transaction.
    return Promise.all(
      newCandidates.map(async ({ doc, fileHash }) => {
        const dataUri = `data:${doc.mimeType};base64,${doc.content}`;
        const { fileUrl, imageUrl } =
          await this.cloudinaryProvider.uploadInvoiceToCloudinary(dataUri);
        return { fileUrl, imageUrl, fileHash };
      }),
    );
  }

  /**
   * Insert already-uploaded documents under the grant tenant, attributing them
   * to the recognized issuing business as the document counterparty (creditor).
   * One charge owns the documents; documents land as UNPROCESSED
   * (classification/OCR happens later via the normal flow). Runs entirely inside
   * the caller's transaction with no network I/O. Returns the created charge id.
   */
  private async insertPreparedDocuments(
    client: PoolClient,
    args: {
      tenantId: string;
      businessId: string | null;
      messageId: string;
      preparedDocuments: PreparedDocument[];
    },
  ): Promise<string> {
    const { tenantId, businessId, messageId, preparedDocuments } = args;

    const [charge] = await insertIngestCharge.run(
      {
        ownerId: tenantId,
        userDescription: `email-ingestion: ${messageId}`,
        accountantStatus: 'UNAPPROVED',
      },
      client,
    );
    const chargeId = charge.id;

    for (const doc of preparedDocuments) {
      await insertIngestDocument.run(
        {
          ownerId: tenantId,
          chargeId,
          // Null when no business was recognized.
          creditorId: businessId,
          documentType: DocumentType.Unprocessed,
          fileUrl: doc.fileUrl,
          imageUrl: doc.imageUrl,
          fileHash: doc.fileHash,
        },
        client,
      );
    }

    return chargeId;
  }

  private async persistIdempotencyAndDedup(args: {
    idempotencyKey: string;
    tenantId: string;
    fingerprint: string;
    outcome: IngestOutcome;
    ingestId: string | null;
    auditId: string;
    correlationId: string;
    client: PoolClient;
  }): Promise<{ ingestId: string | null; auditId: string }> {
    const {
      idempotencyKey,
      tenantId,
      fingerprint,
      outcome,
      ingestId,
      auditId,
      correlationId,
      client,
    } = args;

    const idemRows = await insertIdempotencyKey.run(
      { idempotencyKey, ownerId: tenantId, outcome, ingestId, auditId },
      client,
    );

    await insertDedupFingerprint.run(
      { ownerId: tenantId, fingerprint, outcome, ingestId, correlationId },
      client,
    );

    if (idemRows.length > 0) {
      return { ingestId: idemRows[0].ingest_id, auditId: idemRows[0].audit_id };
    }

    // Conflict: a concurrent request inserted the idempotency record first.
    // Fetch the stored record so we return the IDs that were actually persisted.
    const existing = await checkIdempotencyKey.run({ idempotencyKey, ownerId: tenantId }, client);
    if (existing.length > 0) {
      return { ingestId: existing[0].ingest_id, auditId: existing[0].audit_id };
    }
    return { ingestId, auditId };
  }
}
