import { randomUUID } from 'node:crypto';
import { Injectable, Scope } from 'graphql-modules';
import { sql } from '@pgtyped/runtime';
import { DBProvider } from '../../app-providers/db.provider.js';
import { IngestOutcome, IngestReasonCode } from '../contracts.js';
import type { EmailIngestionControlProvider } from './email-ingestion-control.provider.js';
import { computeDedupFingerprint } from './email-ingestion-idempotency.provider.js';

// ---------------------------------------------------------------------------
// Inline query types (normally generated by `yarn generate:sql`)
// ---------------------------------------------------------------------------

interface ICheckIdempotencyForIngestQuery {
  params: { idempotencyKey: string; ownerId: string };
  result: {
    id: string;
    idempotency_key: string;
    owner_id: string;
    outcome: string;
    ingest_id: string | null;
    audit_id: string;
    created_at: Date;
  };
}

interface IInsertIdempotencyForIngestQuery {
  params: {
    idempotencyKey: string;
    ownerId: string;
    outcome: string;
    ingestId: string | null;
    auditId: string;
  };
  result: {
    id: string;
    idempotency_key: string;
    owner_id: string;
    outcome: string;
    ingest_id: string | null;
    audit_id: string;
    created_at: Date;
  };
}

interface ICheckDedupForIngestQuery {
  params: { ownerId: string; fingerprint: string };
  result: {
    id: string;
    owner_id: string;
    fingerprint: string;
    outcome: string;
    ingest_id: string | null;
    correlation_id: string | null;
    created_at: Date;
  };
}

interface IInsertDedupForIngestQuery {
  params: {
    ownerId: string;
    fingerprint: string;
    outcome: string;
    ingestId: string | null;
    correlationId: string | null;
  };
  result: {
    id: string;
    owner_id: string;
    fingerprint: string;
    outcome: string;
    ingest_id: string | null;
    correlation_id: string | null;
    created_at: Date;
  };
}

interface IInsertQuarantineForIngestQuery {
  params: {
    reasonCode: string;
    tenantCandidate: string;
    messageId: string | null;
    rawMessageHash: string | null;
    correlationId: string;
  };
  result: { id: string };
}

// ---------------------------------------------------------------------------
// SQL queries
// ---------------------------------------------------------------------------

const checkIdempotencyKey = sql<ICheckIdempotencyForIngestQuery>`
  SELECT id, idempotency_key, owner_id, outcome, ingest_id, audit_id, created_at
    FROM accounter_schema.email_ingestion_idempotency_keys
   WHERE idempotency_key = $idempotencyKey
     AND owner_id = $ownerId
   LIMIT 1
`;

const insertIdempotencyKey = sql<IInsertIdempotencyForIngestQuery>`
  INSERT INTO accounter_schema.email_ingestion_idempotency_keys
    (idempotency_key, owner_id, outcome, ingest_id, audit_id)
  VALUES ($idempotencyKey, $ownerId, $outcome, $ingestId, $auditId)
  ON CONFLICT (idempotency_key, owner_id) DO NOTHING
  RETURNING id, idempotency_key, owner_id, outcome, ingest_id, audit_id, created_at
`;

const checkDedupFingerprint = sql<ICheckDedupForIngestQuery>`
  SELECT id, owner_id, fingerprint, outcome, ingest_id, correlation_id, created_at
    FROM accounter_schema.email_ingestion_dedup_fingerprints
   WHERE owner_id = $ownerId
     AND fingerprint = $fingerprint
   LIMIT 1
`;

const insertDedupFingerprint = sql<IInsertDedupForIngestQuery>`
  INSERT INTO accounter_schema.email_ingestion_dedup_fingerprints
    (owner_id, fingerprint, outcome, ingest_id, correlation_id)
  VALUES ($ownerId, $fingerprint, $outcome, $ingestId, $correlationId)
  ON CONFLICT (owner_id, fingerprint) DO NOTHING
  RETURNING id, owner_id, fingerprint, outcome, ingest_id, correlation_id, created_at
`;

const insertQuarantine = sql<IInsertQuarantineForIngestQuery>`
  INSERT INTO accounter_schema.email_ingestion_quarantine
    (reason_code, tenant_candidate, message_id, raw_message_hash, correlation_id)
  VALUES ($reasonCode, $tenantCandidate, $messageId, $rawMessageHash, $correlationId)
  RETURNING id
`;

// ---------------------------------------------------------------------------
// Public input / output types
// ---------------------------------------------------------------------------

export type IngestInput = {
  grantJti: string;
  idempotencyKey: string;
  tenantId: string;
  messageId: string;
  rawMessageHash: string;
  correlationId?: string;
  extractedDocuments: Array<{
    hash: string;
    sizeBytes: number;
    mimeType: string;
    filename?: string | null;
  }>;
};

export type IngestResult =
  | { outcome: typeof IngestOutcome.INSERTED; ingestId: string; auditId: string }
  | {
      outcome: typeof IngestOutcome.DUPLICATE;
      existingIngestId: string | null;
      auditId: string;
    }
  | { outcome: typeof IngestOutcome.QUARANTINED; auditId: string; reasonCode: string }
  | { outcome: typeof IngestOutcome.REJECTED; reasonCode: string };

// ---------------------------------------------------------------------------
// Provider
// ---------------------------------------------------------------------------

/**
 * Orchestrates the v2 ingest flow for gateway-initiated ingestion.
 *
 * Uses DBProvider (raw pool) because the caller presents a gateway_control_plane
 * auth token with an empty businessId — TenantAwareDBClient would throw
 * UNAUTHENTICATED. Tenant isolation is enforced explicitly via owner_id
 * parameters in every query plus the RLS policies on the underlying tables.
 *
 * Flow: grant validation → idempotency check → dedup check → quarantine or insert.
 */
@Injectable({
  scope: Scope.Singleton,
  global: true,
})
export class EmailIngestionIngestProvider {
  constructor(
    private dbProvider: DBProvider,
    private controlProvider: EmailIngestionControlProvider,
  ) {}

  async performIngest(input: IngestInput): Promise<IngestResult> {
    const {
      grantJti,
      idempotencyKey,
      tenantId,
      messageId,
      rawMessageHash,
      correlationId,
      extractedDocuments,
    } = input;

    // 1. Validate and atomically consume the grant.
    const grantResult = await this.controlProvider.validateAndConsumeGrant({
      jti: grantJti,
      tenantId,
      messageId,
      rawMessageHash,
    });

    if (!grantResult.valid) {
      return { outcome: IngestOutcome.REJECTED, reasonCode: grantResult.reason };
    }

    const pool = this.dbProvider.pool;

    // 2. Idempotency check — return prior outcome if this key was already processed.
    const idemRows = await checkIdempotencyKey.run({ idempotencyKey, ownerId: tenantId }, pool);
    if (idemRows.length > 0) {
      const r = idemRows[0];
      return {
        outcome: IngestOutcome.DUPLICATE,
        existingIngestId: r.ingest_id,
        auditId: r.audit_id,
      };
    }

    // 3. Dedup fingerprint check — detect identical content re-delivery.
    const fingerprint = computeDedupFingerprint(tenantId, rawMessageHash);
    const dedupRows = await checkDedupFingerprint.run({ ownerId: tenantId, fingerprint }, pool);
    if (dedupRows.length > 0) {
      const r = dedupRows[0];
      return {
        outcome: IngestOutcome.DUPLICATE,
        existingIngestId: r.ingest_id,
        auditId: randomUUID(),
      };
    }

    const corrId = correlationId ?? randomUUID();

    // 4. Quarantine if no documents were extracted.
    if (extractedDocuments.length === 0) {
      await insertQuarantine.run(
        {
          reasonCode: IngestReasonCode.NO_DOCUMENTS,
          tenantCandidate: tenantId,
          messageId,
          rawMessageHash,
          correlationId: corrId,
        },
        pool,
      );

      const auditId = randomUUID();
      await this.persistIdempotencyAndDedup({
        idempotencyKey,
        tenantId,
        fingerprint,
        outcome: IngestOutcome.QUARANTINED,
        ingestId: null,
        auditId,
        correlationId: corrId,
        pool,
      });

      return {
        outcome: IngestOutcome.QUARANTINED,
        auditId,
        reasonCode: IngestReasonCode.NO_DOCUMENTS,
      };
    }

    // 5. Happy path: record the ingest.
    const ingestId = randomUUID();
    const auditId = randomUUID();

    const idemResult = await this.persistIdempotencyAndDedup({
      idempotencyKey,
      tenantId,
      fingerprint,
      outcome: IngestOutcome.INSERTED,
      ingestId,
      auditId,
      correlationId: corrId,
      pool,
    });

    return {
      outcome: IngestOutcome.INSERTED,
      ingestId: idemResult.ingestId ?? ingestId,
      auditId: idemResult.auditId,
    };
  }

  private async persistIdempotencyAndDedup(args: {
    idempotencyKey: string;
    tenantId: string;
    fingerprint: string;
    outcome: IngestOutcome;
    ingestId: string | null;
    auditId: string;
    correlationId: string;
    pool: DBProvider['pool'];
  }): Promise<{ ingestId: string | null; auditId: string }> {
    const {
      idempotencyKey,
      tenantId,
      fingerprint,
      outcome,
      ingestId,
      auditId,
      correlationId,
      pool,
    } = args;

    const idemRows = await insertIdempotencyKey.run(
      { idempotencyKey, ownerId: tenantId, outcome, ingestId, auditId },
      pool,
    );

    await insertDedupFingerprint.run(
      { ownerId: tenantId, fingerprint, outcome, ingestId, correlationId },
      pool,
    );

    if (idemRows.length > 0) {
      return { ingestId: idemRows[0].ingest_id, auditId: idemRows[0].audit_id };
    }
    return { ingestId, auditId };
  }
}
