import {
  Currency,
  DocumentType,
  GreenInvoiceCountry,
  GreenInvoiceDiscountType,
  GreenInvoiceDocumentLang,
  GreenInvoicePaymentAppType,
  GreenInvoicePaymentCardType,
  GreenInvoicePaymentDealType,
  GreenInvoicePaymentSubType,
  GreenInvoicePaymentType,
  GreenInvoiceVatType,
} from '../../../../../gql/graphql.js';

// Helper functions to get enum options with labels
export const getDocumentLangOptions = () => [
  { value: GreenInvoiceDocumentLang.English, label: 'English' },
  { value: GreenInvoiceDocumentLang.Hebrew, label: 'Hebrew' },
];

export const getCurrencyOptions = () => [
  { value: Currency.Ils, label: 'Israeli Shekel (ILS)' },
  { value: Currency.Usd, label: 'US Dollar (USD)' },
  { value: Currency.Eur, label: 'Euro (EUR)' },
  { value: Currency.Gbp, label: 'British Pound (GBP)' },
  { value: Currency.Jpy, label: 'Japanese Yen (JPY)' },
  // { value: Currency.Chf, label: 'Swiss Franc (CHF)' },
  // { value: Currency.Cny, label: 'Chinese Yuan (CNY)' },
  { value: Currency.Aud, label: 'Australian Dollar (AUD)' },
  { value: Currency.Cad, label: 'Canadian Dollar (CAD)' },
  // { value: Currency.Rub, label: 'Russian Ruble (RUB)' },
  // { value: Currency.Brl, label: 'Brazilian Real (BRL)' },
  // { value: Currency.Hkd, label: 'Hong Kong Dollar (HKD)' },
  // { value: Currency.Sgd, label: 'Singapore Dollar (SGD)' },
  // { value: Currency.Thb, label: 'Thai Baht (THB)' },
  // { value: Currency.Mxn, label: 'Mexican Peso (MXN)' },
  // { value: Currency.Try, label: 'Turkish Lira (TRY)' },
  // { value: Currency.Nzd, label: 'New Zealand Dollar (NZD)' },
  { value: Currency.Sek, label: 'Swedish Krona (SEK)' },
  // { value: Currency.Nok, label: 'Norwegian Krone (NOK)' },
  // { value: Currency.Dkk, label: 'Danish Krone (DKK)' },
  // { value: Currency.Krw, label: 'South Korean Won (KRW)' },
  // { value: Currency.Inr, label: 'Indian Rupee (INR)' },
  // { value: Currency.Idr, label: 'Indonesian Rupiah (IDR)' },
  // { value: Currency.Pln, label: 'Polish Zloty (PLN)' },
  // { value: Currency.Ron, label: 'Romanian Leu (RON)' },
  // { value: Currency.Zar, label: 'South African Rand (ZAR)' },
  // { value: Currency.Hrk, label: 'Croatian Kuna (HRK)' },
];

export const getVatTypeOptions = () => [
  { value: GreenInvoiceVatType.Default, label: 'Default (Based on business type)' },
  { value: GreenInvoiceVatType.Exempt, label: 'Exempt (VAT free)' },
  { value: GreenInvoiceVatType.Mixed, label: 'Mixed (Contains exempt and due VAT income rows)' },
];

export const getDiscountTypeOptions = () => [
  { value: GreenInvoiceDiscountType.Percentage, label: 'Percentage' },
  { value: GreenInvoiceDiscountType.Sum, label: 'Fixed Amount' },
];

export const getDocumentTypeOptions = () => [
  { value: DocumentType.CreditInvoice, label: 'Credit Note' },
  { value: DocumentType.Invoice, label: 'Tax Invoice' },
  { value: DocumentType.InvoiceReceipt, label: 'Tax Invoice/Receipt' },
  { value: DocumentType.Receipt, label: 'Receipt' },
  // Other = 'OTHER',
  // Proforma = 'PROFORMA',
  // Unprocessed = 'UNPROCESSED'
  // { value: DocumentType.PriceQuote, label: 'Price Quote' },
  // { value: DocumentType.Order, label: 'Order' },
  // { value: DocumentType.DeliveryNote, label: 'Delivery Note' },
  // { value: DocumentType.ReturnNote, label: 'Return Note' },
  // { value: DocumentType.TransactionInvoice, label: 'Transaction Invoice' },
  // { value: DocumentType.DonationReceipt, label: 'Donation Receipt' },
  // { value: DocumentType.PurchaseOrder, label: 'Purchase Order' },
  // { value: DocumentType.DepositReceipt, label: 'Deposit Receipt' },
  // { value: DocumentType.DepositWithdrawal, label: 'Deposit Withdrawal' },
];

export const getCountryOptions = () => [
  // Popular countries first
  { value: GreenInvoiceCountry.Il, label: 'Israel' },
  { value: GreenInvoiceCountry.Us, label: 'United States' },
  { value: GreenInvoiceCountry.Gb, label: 'United Kingdom' },
  { value: GreenInvoiceCountry.De, label: 'Germany' },
  { value: GreenInvoiceCountry.Fr, label: 'France' },
  { value: GreenInvoiceCountry.Ca, label: 'Canada' },
  { value: GreenInvoiceCountry.Au, label: 'Australia' },
  { value: GreenInvoiceCountry.Jp, label: 'Japan' },
  { value: GreenInvoiceCountry.Cn, label: 'China' },
  { value: GreenInvoiceCountry.In, label: 'India' },
  // All other countries alphabetically
  { value: GreenInvoiceCountry.Af, label: 'Afghanistan' },
  { value: GreenInvoiceCountry.Ax, label: 'Åland Islands' },
  { value: GreenInvoiceCountry.Al, label: 'Albania' },
  { value: GreenInvoiceCountry.Dz, label: 'Algeria' },
  { value: GreenInvoiceCountry.As, label: 'American Samoa' },
  { value: GreenInvoiceCountry.Ad, label: 'Andorra' },
  { value: GreenInvoiceCountry.Ao, label: 'Angola' },
  { value: GreenInvoiceCountry.Ai, label: 'Anguilla' },
  { value: GreenInvoiceCountry.Aq, label: 'Antarctica' },
  { value: GreenInvoiceCountry.Ag, label: 'Antigua and Barbuda' },
  { value: GreenInvoiceCountry.Ar, label: 'Argentina' },
  { value: GreenInvoiceCountry.Am, label: 'Armenia' },
  { value: GreenInvoiceCountry.Aw, label: 'Aruba' },
  { value: GreenInvoiceCountry.At, label: 'Austria' },
  { value: GreenInvoiceCountry.Az, label: 'Azerbaijan' },
  { value: GreenInvoiceCountry.Bs, label: 'Bahamas' },
  { value: GreenInvoiceCountry.Bh, label: 'Bahrain' },
  { value: GreenInvoiceCountry.Bd, label: 'Bangladesh' },
  { value: GreenInvoiceCountry.Bb, label: 'Barbados' },
  { value: GreenInvoiceCountry.By, label: 'Belarus' },
  { value: GreenInvoiceCountry.Be, label: 'Belgium' },
  { value: GreenInvoiceCountry.Bz, label: 'Belize' },
  { value: GreenInvoiceCountry.Bj, label: 'Benin' },
  { value: GreenInvoiceCountry.Bm, label: 'Bermuda' },
  { value: GreenInvoiceCountry.Bt, label: 'Bhutan' },
  { value: GreenInvoiceCountry.Bo, label: 'Bolivia' },
  {
    value: GreenInvoiceCountry.Bq,
    label: 'Bonaire, Sint Eustatius and Saba',
  },
  { value: GreenInvoiceCountry.Ba, label: 'Bosnia and Herzegovina' },
  { value: GreenInvoiceCountry.Bw, label: 'Botswana' },
  { value: GreenInvoiceCountry.Bv, label: 'Bouvet Island' },
  { value: GreenInvoiceCountry.Br, label: 'Brazil' },
  {
    value: GreenInvoiceCountry.Io,
    label: 'British Indian Ocean Territory',
  },
  { value: GreenInvoiceCountry.Vg, label: 'British Virgin Islands' },
  { value: GreenInvoiceCountry.Bn, label: 'Brunei' },
  { value: GreenInvoiceCountry.Bg, label: 'Bulgaria' },
  { value: GreenInvoiceCountry.Bf, label: 'Burkina Faso' },
  { value: GreenInvoiceCountry.Bi, label: 'Burundi' },
  { value: GreenInvoiceCountry.Kh, label: 'Cambodia' },
  { value: GreenInvoiceCountry.Cm, label: 'Cameroon' },
  { value: GreenInvoiceCountry.Cv, label: 'Cape Verde' },
  { value: GreenInvoiceCountry.Ky, label: 'Cayman Islands' },
  { value: GreenInvoiceCountry.Cf, label: 'Central African Republic' },
  { value: GreenInvoiceCountry.Td, label: 'Chad' },
  { value: GreenInvoiceCountry.Cl, label: 'Chile' },
  { value: GreenInvoiceCountry.Cx, label: 'Christmas Island' },
  { value: GreenInvoiceCountry.Cc, label: 'Cocos Islands' },
  { value: GreenInvoiceCountry.Co, label: 'Colombia' },
  { value: GreenInvoiceCountry.Km, label: 'Comoros' },
  { value: GreenInvoiceCountry.Ck, label: 'Cook Islands' },
  { value: GreenInvoiceCountry.Cr, label: 'Costa Rica' },
  { value: GreenInvoiceCountry.Ci, label: "Côte d'Ivoire" },
  { value: GreenInvoiceCountry.Hr, label: 'Croatia' },
  { value: GreenInvoiceCountry.Cu, label: 'Cuba' },
  { value: GreenInvoiceCountry.Cw, label: 'Curaçao' },
  { value: GreenInvoiceCountry.Cy, label: 'Cyprus' },
  { value: GreenInvoiceCountry.Cz, label: 'Czech Republic' },
  {
    value: GreenInvoiceCountry.Cd,
    label: 'Democratic Republic of the Congo',
  },
  { value: GreenInvoiceCountry.Dk, label: 'Denmark' },
  { value: GreenInvoiceCountry.Dj, label: 'Djibouti' },
  { value: GreenInvoiceCountry.Dm, label: 'Dominica' },
  { value: GreenInvoiceCountry.Do, label: 'Dominican Republic' },
  { value: GreenInvoiceCountry.Ec, label: 'Ecuador' },
  { value: GreenInvoiceCountry.Eg, label: 'Egypt' },
  { value: GreenInvoiceCountry.Sv, label: 'El Salvador' },
  { value: GreenInvoiceCountry.Gq, label: 'Equatorial Guinea' },
  { value: GreenInvoiceCountry.Er, label: 'Eritrea' },
  { value: GreenInvoiceCountry.Ee, label: 'Estonia' },
  { value: GreenInvoiceCountry.Sz, label: 'Eswatini' },
  { value: GreenInvoiceCountry.Et, label: 'Ethiopia' },
  { value: GreenInvoiceCountry.Fk, label: 'Falkland Islands' },
  { value: GreenInvoiceCountry.Fo, label: 'Faroe Islands' },
  { value: GreenInvoiceCountry.Fj, label: 'Fiji' },
  { value: GreenInvoiceCountry.Fi, label: 'Finland' },
  { value: GreenInvoiceCountry.Gf, label: 'French Guiana' },
  { value: GreenInvoiceCountry.Pf, label: 'French Polynesia' },
  { value: GreenInvoiceCountry.Tf, label: 'French Southern Territories' },
  { value: GreenInvoiceCountry.Ga, label: 'Gabon' },
  { value: GreenInvoiceCountry.Gm, label: 'Gambia' },
  { value: GreenInvoiceCountry.Ge, label: 'Georgia' },
  { value: GreenInvoiceCountry.Gh, label: 'Ghana' },
  { value: GreenInvoiceCountry.Gi, label: 'Gibraltar' },
  { value: GreenInvoiceCountry.Gr, label: 'Greece' },
  { value: GreenInvoiceCountry.Gl, label: 'Greenland' },
  { value: GreenInvoiceCountry.Gd, label: 'Grenada' },
  { value: GreenInvoiceCountry.Gp, label: 'Guadeloupe' },
  { value: GreenInvoiceCountry.Gu, label: 'Guam' },
  { value: GreenInvoiceCountry.Gt, label: 'Guatemala' },
  { value: GreenInvoiceCountry.Gg, label: 'Guernsey' },
  { value: GreenInvoiceCountry.Gn, label: 'Guinea' },
  { value: GreenInvoiceCountry.Gw, label: 'Guinea-Bissau' },
  { value: GreenInvoiceCountry.Gy, label: 'Guyana' },
  { value: GreenInvoiceCountry.Ht, label: 'Haiti' },
  {
    value: GreenInvoiceCountry.Hm,
    label: 'Heard Island and McDonald Islands',
  },
  { value: GreenInvoiceCountry.Hn, label: 'Honduras' },
  { value: GreenInvoiceCountry.Hk, label: 'Hong Kong' },
  { value: GreenInvoiceCountry.Hu, label: 'Hungary' },
  { value: GreenInvoiceCountry.Is, label: 'Iceland' },
  { value: GreenInvoiceCountry.Id, label: 'Indonesia' },
  { value: GreenInvoiceCountry.Ir, label: 'Iran' },
  { value: GreenInvoiceCountry.Iq, label: 'Iraq' },
  { value: GreenInvoiceCountry.Ie, label: 'Ireland' },
  { value: GreenInvoiceCountry.Im, label: 'Isle of Man' },
  { value: GreenInvoiceCountry.It, label: 'Italy' },
  { value: GreenInvoiceCountry.Jm, label: 'Jamaica' },
  { value: GreenInvoiceCountry.Je, label: 'Jersey' },
  { value: GreenInvoiceCountry.Jo, label: 'Jordan' },
  { value: GreenInvoiceCountry.Kz, label: 'Kazakhstan' },
  { value: GreenInvoiceCountry.Ke, label: 'Kenya' },
  { value: GreenInvoiceCountry.Ki, label: 'Kiribati' },
  { value: GreenInvoiceCountry.Xk, label: 'Kosovo' },
  { value: GreenInvoiceCountry.Kw, label: 'Kuwait' },
  { value: GreenInvoiceCountry.Kg, label: 'Kyrgyzstan' },
  { value: GreenInvoiceCountry.La, label: 'Laos' },
  { value: GreenInvoiceCountry.Lv, label: 'Latvia' },
  { value: GreenInvoiceCountry.Lb, label: 'Lebanon' },
  { value: GreenInvoiceCountry.Ls, label: 'Lesotho' },
  { value: GreenInvoiceCountry.Lr, label: 'Liberia' },
  { value: GreenInvoiceCountry.Ly, label: 'Libya' },
  { value: GreenInvoiceCountry.Li, label: 'Liechtenstein' },
  { value: GreenInvoiceCountry.Lt, label: 'Lithuania' },
  { value: GreenInvoiceCountry.Lu, label: 'Luxembourg' },
  { value: GreenInvoiceCountry.Mo, label: 'Macao' },
  { value: GreenInvoiceCountry.Mg, label: 'Madagascar' },
  { value: GreenInvoiceCountry.Mw, label: 'Malawi' },
  { value: GreenInvoiceCountry.My, label: 'Malaysia' },
  { value: GreenInvoiceCountry.Mv, label: 'Maldives' },
  { value: GreenInvoiceCountry.Ml, label: 'Mali' },
  { value: GreenInvoiceCountry.Mt, label: 'Malta' },
  { value: GreenInvoiceCountry.Mh, label: 'Marshall Islands' },
  { value: GreenInvoiceCountry.Mq, label: 'Martinique' },
  { value: GreenInvoiceCountry.Mr, label: 'Mauritania' },
  { value: GreenInvoiceCountry.Mu, label: 'Mauritius' },
  { value: GreenInvoiceCountry.Yt, label: 'Mayotte' },
  { value: GreenInvoiceCountry.Mx, label: 'Mexico' },
  { value: GreenInvoiceCountry.Fm, label: 'Micronesia' },
  { value: GreenInvoiceCountry.Md, label: 'Moldova' },
  { value: GreenInvoiceCountry.Mc, label: 'Monaco' },
  { value: GreenInvoiceCountry.Mn, label: 'Mongolia' },
  { value: GreenInvoiceCountry.Me, label: 'Montenegro' },
  { value: GreenInvoiceCountry.Ms, label: 'Montserrat' },
  { value: GreenInvoiceCountry.Ma, label: 'Morocco' },
  { value: GreenInvoiceCountry.Mz, label: 'Mozambique' },
  { value: GreenInvoiceCountry.Mm, label: 'Myanmar' },
  { value: GreenInvoiceCountry.Na, label: 'Namibia' },
  { value: GreenInvoiceCountry.Nr, label: 'Nauru' },
  { value: GreenInvoiceCountry.Np, label: 'Nepal' },
  { value: GreenInvoiceCountry.Nl, label: 'Netherlands' },
  { value: GreenInvoiceCountry.Nc, label: 'New Caledonia' },
  { value: GreenInvoiceCountry.Nz, label: 'New Zealand' },
  { value: GreenInvoiceCountry.Ni, label: 'Nicaragua' },
  { value: GreenInvoiceCountry.Ne, label: 'Niger' },
  { value: GreenInvoiceCountry.Ng, label: 'Nigeria' },
  { value: GreenInvoiceCountry.Nu, label: 'Niue' },
  { value: GreenInvoiceCountry.Nf, label: 'Norfolk Island' },
  { value: GreenInvoiceCountry.Kp, label: 'North Korea' },
  { value: GreenInvoiceCountry.Mk, label: 'North Macedonia' },
  { value: GreenInvoiceCountry.Mp, label: 'Northern Mariana Islands' },
  { value: GreenInvoiceCountry.No, label: 'Norway' },
  { value: GreenInvoiceCountry.Om, label: 'Oman' },
  { value: GreenInvoiceCountry.Pk, label: 'Pakistan' },
  { value: GreenInvoiceCountry.Pw, label: 'Palau' },
  { value: GreenInvoiceCountry.Ps, label: 'Palestine' },
  { value: GreenInvoiceCountry.Pa, label: 'Panama' },
  { value: GreenInvoiceCountry.Pg, label: 'Papua New Guinea' },
  { value: GreenInvoiceCountry.Py, label: 'Paraguay' },
  { value: GreenInvoiceCountry.Pe, label: 'Peru' },
  { value: GreenInvoiceCountry.Ph, label: 'Philippines' },
  { value: GreenInvoiceCountry.Pn, label: 'Pitcairn Islands' },
  { value: GreenInvoiceCountry.Pl, label: 'Poland' },
  { value: GreenInvoiceCountry.Pt, label: 'Portugal' },
  { value: GreenInvoiceCountry.Pr, label: 'Puerto Rico' },
  { value: GreenInvoiceCountry.Qa, label: 'Qatar' },
  { value: GreenInvoiceCountry.Cg, label: 'Republic of the Congo' },
  { value: GreenInvoiceCountry.Re, label: 'Réunion' },
  { value: GreenInvoiceCountry.Ro, label: 'Romania' },
  { value: GreenInvoiceCountry.Ru, label: 'Russia' },
  { value: GreenInvoiceCountry.Rw, label: 'Rwanda' },
  { value: GreenInvoiceCountry.Bl, label: 'Saint Barthélemy' },
  { value: GreenInvoiceCountry.Sh, label: 'Saint Helena' },
  { value: GreenInvoiceCountry.Kn, label: 'Saint Kitts and Nevis' },
  { value: GreenInvoiceCountry.Lc, label: 'Saint Lucia' },
  { value: GreenInvoiceCountry.Mf, label: 'Saint Martin' },
  { value: GreenInvoiceCountry.Pm, label: 'Saint Pierre and Miquelon' },
  {
    value: GreenInvoiceCountry.Vc,
    label: 'Saint Vincent and the Grenadines',
  },
  { value: GreenInvoiceCountry.Ws, label: 'Samoa' },
  { value: GreenInvoiceCountry.Sm, label: 'San Marino' },
  { value: GreenInvoiceCountry.St, label: 'São Tomé and Príncipe' },
  { value: GreenInvoiceCountry.Sa, label: 'Saudi Arabia' },
  { value: GreenInvoiceCountry.Sn, label: 'Senegal' },
  { value: GreenInvoiceCountry.Rs, label: 'Serbia' },
  { value: GreenInvoiceCountry.Sc, label: 'Seychelles' },
  { value: GreenInvoiceCountry.Sl, label: 'Sierra Leone' },
  { value: GreenInvoiceCountry.Sg, label: 'Singapore' },
  { value: GreenInvoiceCountry.Sx, label: 'Sint Maarten' },
  { value: GreenInvoiceCountry.Sk, label: 'Slovakia' },
  { value: GreenInvoiceCountry.Si, label: 'Slovenia' },
  { value: GreenInvoiceCountry.Sb, label: 'Solomon Islands' },
  { value: GreenInvoiceCountry.So, label: 'Somalia' },
  { value: GreenInvoiceCountry.Za, label: 'South Africa' },
  {
    value: GreenInvoiceCountry.Gs,
    label: 'South Georgia and the South Sandwich Islands',
  },
  { value: GreenInvoiceCountry.Kr, label: 'South Korea' },
  { value: GreenInvoiceCountry.Ss, label: 'South Sudan' },
  { value: GreenInvoiceCountry.Es, label: 'Spain' },
  { value: GreenInvoiceCountry.Lk, label: 'Sri Lanka' },
  { value: GreenInvoiceCountry.Sd, label: 'Sudan' },
  { value: GreenInvoiceCountry.Sr, label: 'Suriname' },
  { value: GreenInvoiceCountry.Sj, label: 'Svalbard and Jan Mayen' },
  { value: GreenInvoiceCountry.Se, label: 'Sweden' },
  { value: GreenInvoiceCountry.Ch, label: 'Switzerland' },
  { value: GreenInvoiceCountry.Sy, label: 'Syria' },
  { value: GreenInvoiceCountry.Tw, label: 'Taiwan' },
  { value: GreenInvoiceCountry.Tj, label: 'Tajikistan' },
  { value: GreenInvoiceCountry.Tz, label: 'Tanzania' },
  { value: GreenInvoiceCountry.Th, label: 'Thailand' },
  { value: GreenInvoiceCountry.Tl, label: 'Timor-Leste' },
  { value: GreenInvoiceCountry.Tg, label: 'Togo' },
  { value: GreenInvoiceCountry.Tk, label: 'Tokelau' },
  { value: GreenInvoiceCountry.To, label: 'Tonga' },
  { value: GreenInvoiceCountry.Tt, label: 'Trinidad and Tobago' },
  { value: GreenInvoiceCountry.Tn, label: 'Tunisia' },
  { value: GreenInvoiceCountry.Tr, label: 'Turkey' },
  { value: GreenInvoiceCountry.Tm, label: 'Turkmenistan' },
  { value: GreenInvoiceCountry.Tc, label: 'Turks and Caicos Islands' },
  { value: GreenInvoiceCountry.Tv, label: 'Tuvalu' },
  { value: GreenInvoiceCountry.Ug, label: 'Uganda' },
  { value: GreenInvoiceCountry.Ua, label: 'Ukraine' },
  { value: GreenInvoiceCountry.Ae, label: 'United Arab Emirates' },
  {
    value: GreenInvoiceCountry.Um,
    label: 'United States Minor Outlying Islands',
  },
  { value: GreenInvoiceCountry.Uy, label: 'Uruguay' },
  { value: GreenInvoiceCountry.Vi, label: 'US Virgin Islands' },
  { value: GreenInvoiceCountry.Uz, label: 'Uzbekistan' },
  { value: GreenInvoiceCountry.Vu, label: 'Vanuatu' },
  { value: GreenInvoiceCountry.Va, label: 'Vatican City' },
  { value: GreenInvoiceCountry.Ve, label: 'Venezuela' },
  { value: GreenInvoiceCountry.Vn, label: 'Vietnam' },
  { value: GreenInvoiceCountry.Wf, label: 'Wallis and Futuna' },
  { value: GreenInvoiceCountry.Eh, label: 'Western Sahara' },
  { value: GreenInvoiceCountry.Ye, label: 'Yemen' },
  { value: GreenInvoiceCountry.Zm, label: 'Zambia' },
  { value: GreenInvoiceCountry.Zw, label: 'Zimbabwe' },
];

export const getPaymentTypeOptions = () => [
  { value: GreenInvoicePaymentType.TaxDeduction, label: 'Tax deduction (ניכוי במקור)' },
  { value: GreenInvoicePaymentType.Cash, label: 'Cash (מזומן)' },
  { value: GreenInvoicePaymentType.Cheque, label: 'Cheque (צ׳ק)' },
  { value: GreenInvoicePaymentType.CreditCard, label: 'Credit card (כרטיס אשראי)' },
  { value: GreenInvoicePaymentType.WireTransfer, label: 'Wire-transfer (העברה בנקאית)' },
  { value: GreenInvoicePaymentType.Paypal, label: 'PayPal (פייפאל)' },
  { value: GreenInvoicePaymentType.OtherDeduction, label: 'Other deduction (ניכוי אחר)' },
  { value: GreenInvoicePaymentType.PaymentApp, label: 'Payment app (אפליקציית תשלום)' },
  { value: GreenInvoicePaymentType.Other, label: 'Other (אחר)' },
];

export const getSubTypeOptions = () => [
  { value: GreenInvoicePaymentSubType.Bitcoin, label: 'Bitcoin (ביטקוין)' },
  { value: GreenInvoicePaymentSubType.MoneyEqual, label: 'Money-equal (שווה כסף)' },
  { value: GreenInvoicePaymentSubType.VCheck, label: 'V-Check' },
  { value: GreenInvoicePaymentSubType.GiftCard, label: 'Gift card (שובר מתנה)' },
  {
    value: GreenInvoicePaymentSubType.NiiEmployeeDeduction,
    label: 'NII employee deduction (ניכוי חלק עובד ביטוח לאומי)',
  },
  { value: GreenInvoicePaymentSubType.Ethereum, label: 'Ethereum (אתריום)' },
  { value: GreenInvoicePaymentSubType.BuymeVoucher, label: 'BUYME Voucher (BUYME שובר)' },
  { value: GreenInvoicePaymentSubType.Payoneer, label: 'Payoneer' },
];

export const getAppTypeOptions = () => [
  { value: GreenInvoicePaymentAppType.Bit, label: 'Bit' },
  { value: GreenInvoicePaymentAppType.PayByPepper, label: 'Pay (by Pepper)' },
  { value: GreenInvoicePaymentAppType.Paybox, label: 'PayBox' },
  { value: GreenInvoicePaymentAppType.Culo, label: 'Culo' },
  { value: GreenInvoicePaymentAppType.GooglePay, label: 'Google Pay' },
  { value: GreenInvoicePaymentAppType.ApplePay, label: 'Apple Pay' },
];

export const getCardTypeOptions = () => [
  { value: GreenInvoicePaymentCardType.Unknown, label: 'Unknown (לא ידוע)' },
  { value: GreenInvoicePaymentCardType.Isracard, label: 'Isracard (ישראכרט)' },
  { value: GreenInvoicePaymentCardType.Visa, label: 'Visa (ויזה)' },
  { value: GreenInvoicePaymentCardType.Mastercard, label: 'Mastercard (מאסטרקארד)' },
  { value: GreenInvoicePaymentCardType.AmericanExpress, label: 'American Express (אמריקן אקספרס)' },
  { value: GreenInvoicePaymentCardType.Diners, label: 'Diners (דיינרס)' },
];

export const getDealTypeOptions = () => [
  { value: GreenInvoicePaymentDealType.Standard, label: 'Standard (רגיל)' },
  { value: GreenInvoicePaymentDealType.Payments, label: 'Payments (תשלומים)' },
  { value: GreenInvoicePaymentDealType.Credit, label: 'Credit (קרדיט)' },
  { value: GreenInvoicePaymentDealType.Deferred, label: 'Deferred (חיוב נדחה)' },
  { value: GreenInvoicePaymentDealType.Other, label: 'Other (אחר)' },
  { value: GreenInvoicePaymentDealType.Recurring, label: 'Recurring (הוראת קבע)' },
];
