import { type MigrationExecutor } from '../pg-migrator.js';

/**
 * Comment threads on dynamic report nodes.
 *
 * A thread hangs off one node of one template, across every period the template is viewed for:
 * `(owner_id, template_name, node_id)` is its anchor. Node ids are generated by the client and are
 * stable per template only (entity uuids, `branch-<uuid>`, `${owner_id}|${key}`, legacy integers),
 * so the template has to be part of the key.
 *
 * - `dynamic_report_threads` owns the anchor, the resolved state and the last known row text
 *   (`node_label`, for a thread whose node is no longer in the report). It is the single cascade
 *   point: the template FK's `ON UPDATE CASCADE` keeps threads through a rename and
 *   `ON DELETE CASCADE` drops them with the template. Save as new starts clean, because the new
 *   template has a different name.
 * - `dynamic_report_comments` holds the messages. Each one records the view it was written in
 *   (period and scope owner), so a thread seen from another period can say so. `author_id` is the
 *   acting user, with no FK, like `dynamic_report_template_snapshots.created_by`. Deletion is soft
 *   (`deleted_at`): the API stops returning the text, the row stays.
 *
 * Comments are live writes, independent of snapshots: posting one never writes a snapshot, which
 * would rebase every other leaf's diff.
 *
 * `created_at` on comments defaults to `clock_timestamp()` rather than the transaction start, so
 * messages order by when they were actually written. The `(owner_id, id)` unique constraint exists
 * to back the composite FK, which keeps a comment and its thread in the same tenant.
 *
 * RLS for both tables is in `2026-09-28T10-30-00.rls-dynamic-report-comments.ts`.
 */
export default {
  name: '2026-09-28T10-00-00.dynamic-report-comments.sql',
  run: ({ sql }) => sql`
CREATE TABLE IF NOT EXISTS accounter_schema.dynamic_report_threads
(
    id            uuid        DEFAULT uuidv7()          NOT NULL
        CONSTRAINT dynamic_report_threads_pk PRIMARY KEY,
    owner_id      uuid                                  NOT NULL,
    template_name text                                  NOT NULL,
    node_id       text                                  NOT NULL
        CONSTRAINT dynamic_report_threads_node_id_length CHECK (char_length(node_id) BETWEEN 1 AND 200),
    node_kind     text                                  NOT NULL
        CONSTRAINT dynamic_report_threads_node_kind_check CHECK (node_kind IN ('leaf', 'branch')),
    node_label    text                                  NOT NULL,
    resolved_at   timestamptz,
    resolved_by   uuid,
    created_at    timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT dynamic_report_threads_template_fk
        FOREIGN KEY (owner_id, template_name)
            REFERENCES accounter_schema.dynamic_report_templates (owner_id, name)
            ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT dynamic_report_threads_node_unique UNIQUE (owner_id, template_name, node_id),
    CONSTRAINT dynamic_report_threads_owner_id_unique UNIQUE (owner_id, id)
);

CREATE TABLE IF NOT EXISTS accounter_schema.dynamic_report_comments
(
    id             uuid        DEFAULT uuidv7()          NOT NULL
        CONSTRAINT dynamic_report_comments_pk PRIMARY KEY,
    owner_id       uuid                                  NOT NULL,
    thread_id      uuid                                  NOT NULL,
    author_id      uuid                                  NOT NULL,
    content        text                                  NOT NULL
        CONSTRAINT dynamic_report_comments_content_length
            CHECK (char_length(btrim(content)) BETWEEN 1 AND 10000),
    from_date      date                                  NOT NULL,
    to_date        date                                  NOT NULL,
    scope_owner_id uuid                                  NOT NULL,
    created_at     timestamptz DEFAULT clock_timestamp() NOT NULL,
    edited_at      timestamptz,
    deleted_at     timestamptz,
    CONSTRAINT dynamic_report_comments_thread_fk
        FOREIGN KEY (owner_id, thread_id)
            REFERENCES accounter_schema.dynamic_report_threads (owner_id, id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS dynamic_report_comments_thread_index
    ON accounter_schema.dynamic_report_comments (thread_id, created_at, id);
`,
} satisfies MigrationExecutor;
