# Note: This is a composite GitHub Action.
# Docs: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: setup
description: Accounter environment setup

inputs:
  codegen:
    description: Should run GraphQL Codegen?
    default: 'true'
  pgTyped:
    description: Should run PgTyped?
    default: 'true'
  localDB:
    description: Should run local database?
    default: 'true'
  installDependencies:
    description: Should run yarn install?
    default: 'true'
  workingDirectory:
    description: Working dir
    default: ${{ github.workspace }}

runs:
  using: 'composite'
  steps:
    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache Yarn
      uses: actions/cache@v4
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{steps.yarn-cache-dir-path.outputs.dir}}
        key: ${{runner.os}}-19-yarn-${{hashFiles('yarn.lock')}}
        restore-keys: |
          ${{runner.os}}-19-yarn-

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: ${{ inputs.installDependencies == 'true' && 'yarn' }}

    - name: Install Dependencies
      shell: bash
      if: ${{ inputs.installDependencies == 'true' }}
      run: yarn install

    - name: Run Containers
      shell: bash
      if: ${{ inputs.pgTyped == 'true' || inputs.localDB == 'true' }}
      run: |
        source docker/.ci.env
        docker compose \
          -f docker/docker-compose.dev.yml \
          up -d --wait

    - name: Run DB Migrations
      shell: bash
      if: ${{ inputs.pgTyped == 'true' || inputs.localDB == 'true' }}
      run: yarn --cwd packages/migrations db:init

    - name: Generate GraphQL Types
      if: ${{ inputs.codegen == 'true' }}
      shell: bash
      run: yarn codegen

    - name: Generate Postgres Types
      if: ${{ inputs.pgTyped == 'true' && inputs.localDB == 'true' }}
      shell: bash
      run: yarn pgtyped -c docker/pgconfig.json
