# Note: This is a composite GitHub Action.
# Docs: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: setup
description: Accounter environment setup

inputs:
  codegen:
    description: Should run GraphQL Codegen?
    default: 'true'
  pgTyped:
    description: Should run PgTyped?
    default: 'true'
  localDB:
    description: Should run local database?
    default: 'true'
  installDependencies:
    description: Should run yarn install?
    default: 'true'
  workingDirectory:
    description: Working dir
    default: ${{ github.workspace }}

runs:
  using: 'composite'
  steps:
    - name: Install Node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: .node-version

    - name: Install NodeJS
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version-file: .node-version
        cache: ${{ inputs.installDependencies == 'true' && 'yarn' }}

    - name: Install Dependencies
      shell: bash
      if: ${{ inputs.installDependencies == 'true' }}
      run: yarn install

    - name: Run Containers
      shell: bash
      if: ${{ inputs.pgTyped == 'true' || inputs.localDB == 'true' }}
      run: |
        source docker/.ci.env
        docker compose \
          -f docker/docker-compose.dev.yml \
          up -d --wait

    - name: Run DB Migrations
      shell: bash
      if: ${{ inputs.pgTyped == 'true' || inputs.localDB == 'true' }}
      run: yarn db:init

    - name: Generate GraphQL Types
      if: ${{ inputs.codegen == 'true' }}
      shell: bash
      run: yarn generate:graphql

    - name: Generate Postgres Types
      if: ${{ inputs.pgTyped == 'true' && inputs.localDB == 'true' }}
      shell: bash
      run: yarn pgtyped -c docker/pgconfig.json
