import type { IGetAllBusinessTripsResult } from './__generated__/business-trips.types.js';

export * from './__generated__/types.js';
export * from './__generated__/business-trips.types.js';
export * from './__generated__/business-trips-attendees.types.js';
export type {
  business_trip_transaction_type,
  currency,
  IGetAllBusinessTripsExpensesParams,
  IGetAllBusinessTripsExpensesResult,
  IGetAllBusinessTripsExpensesQuery,
  IGetBusinessTripsExpensesByBusinessTripIdsParams,
  IGetBusinessTripsExpensesByBusinessTripIdsResult,
  IGetBusinessTripsExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsExpensesByChargeIdsParams,
  IGetBusinessTripsExpensesByChargeIdsResult,
  IGetBusinessTripsExpensesByChargeIdsQuery,
  IGetBusinessTripsExpensesByIdsParams,
  IGetBusinessTripsExpensesByIdsResult,
  IGetBusinessTripsExpensesByIdsQuery,
  IGetUncategorizedTransactionsByBusinessTripIdParams,
  IGetUncategorizedTransactionsByBusinessTripIdResult,
  IGetUncategorizedTransactionsByBusinessTripIdQuery,
  IUpdateBusinessTripExpenseParams,
  IUpdateBusinessTripExpenseResult,
  IUpdateBusinessTripExpenseQuery,
  IInsertBusinessTripExpenseParams,
  IInsertBusinessTripExpenseResult,
  IInsertBusinessTripExpenseQuery,
  IDeleteBusinessTripExpenseParams,
  IDeleteBusinessTripExpenseResult,
  IDeleteBusinessTripExpenseQuery,
  IGetBusinessTripsExpensesByTransactionIdsParams,
  IGetBusinessTripsExpensesByTransactionIdsResult,
  IGetBusinessTripsExpensesByTransactionIdsQuery,
  IInsertBusinessTripExpenseMatchParams,
  IInsertBusinessTripExpenseMatchResult,
  IInsertBusinessTripExpenseMatchQuery,
  IGetTransactionsByBusinessTripIdParams,
  IGetTransactionsByBusinessTripIdResult,
  IGetTransactionsByBusinessTripIdQuery,
  IDeleteBusinessTripExpenseMatchParams,
  IDeleteBusinessTripExpenseMatchResult,
  IDeleteBusinessTripExpenseMatchQuery,
  IDeleteSpecificBusinessTripExpenseMatchParams,
  IDeleteSpecificBusinessTripExpenseMatchResult,
  IDeleteSpecificBusinessTripExpenseMatchQuery,
} from './__generated__/business-trips-expenses.types.js';
export type {
  flight_class,
  IGetAllBusinessTripsFlightsExpensesParams,
  IGetAllBusinessTripsFlightsExpensesResult,
  IGetAllBusinessTripsFlightsExpensesQuery,
  IGetBusinessTripsFlightsExpensesByBusinessTripIdsParams,
  IGetBusinessTripsFlightsExpensesByBusinessTripIdsResult,
  IGetBusinessTripsFlightsExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsFlightsExpensesByChargeIdsParams,
  IGetBusinessTripsFlightsExpensesByChargeIdsResult,
  IGetBusinessTripsFlightsExpensesByChargeIdsQuery,
  IGetBusinessTripsFlightsExpensesByIdsParams,
  IGetBusinessTripsFlightsExpensesByIdsResult,
  IGetBusinessTripsFlightsExpensesByIdsQuery,
  IUpdateBusinessTripFlightsExpenseParams,
  IUpdateBusinessTripFlightsExpenseResult,
  IUpdateBusinessTripFlightsExpenseQuery,
  IInsertBusinessTripFlightsExpenseParams,
  IInsertBusinessTripFlightsExpenseResult,
  IInsertBusinessTripFlightsExpenseQuery,
  IDeleteBusinessTripFlightsExpenseParams,
  IDeleteBusinessTripFlightsExpenseResult,
  IDeleteBusinessTripFlightsExpenseQuery,
} from './__generated__/business-trips-expenses-flights.types.js';
export type {
  IGetAllBusinessTripsAccommodationsExpensesParams,
  IGetAllBusinessTripsAccommodationsExpensesResult,
  IGetAllBusinessTripsAccommodationsExpensesQuery,
  IGetBusinessTripsAccommodationsExpensesByBusinessTripIdsParams,
  IGetBusinessTripsAccommodationsExpensesByBusinessTripIdsResult,
  IGetBusinessTripsAccommodationsExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsAccommodationsExpensesByChargeIdsParams,
  IGetBusinessTripsAccommodationsExpensesByChargeIdsResult,
  IGetBusinessTripsAccommodationsExpensesByChargeIdsQuery,
  IGetBusinessTripsAccommodationsExpensesByIdsParams,
  IGetBusinessTripsAccommodationsExpensesByIdsResult,
  IGetBusinessTripsAccommodationsExpensesByIdsQuery,
  IUpdateBusinessTripAccommodationsExpenseParams,
  IUpdateBusinessTripAccommodationsExpenseResult,
  IUpdateBusinessTripAccommodationsExpenseQuery,
  IInsertBusinessTripAccommodationsExpenseParams,
  IInsertBusinessTripAccommodationsExpenseResult,
  IInsertBusinessTripAccommodationsExpenseQuery,
  IDeleteBusinessTripAccommodationsExpenseParams,
  IDeleteBusinessTripAccommodationsExpenseResult,
  IDeleteBusinessTripAccommodationsExpenseQuery,
} from './__generated__/business-trips-expenses-accommodations.types.js';
export type {
  IGetAllBusinessTripsTravelAndSubsistenceExpensesParams,
  IGetAllBusinessTripsTravelAndSubsistenceExpensesResult,
  IGetAllBusinessTripsTravelAndSubsistenceExpensesQuery,
  IGetBusinessTripsTravelAndSubsistenceExpensesByBusinessTripIdsParams,
  IGetBusinessTripsTravelAndSubsistenceExpensesByBusinessTripIdsResult,
  IGetBusinessTripsTravelAndSubsistenceExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsTravelAndSubsistenceExpensesByChargeIdsParams,
  IGetBusinessTripsTravelAndSubsistenceExpensesByChargeIdsResult,
  IGetBusinessTripsTravelAndSubsistenceExpensesByChargeIdsQuery,
  IGetBusinessTripsTravelAndSubsistenceExpensesByIdsParams,
  IGetBusinessTripsTravelAndSubsistenceExpensesByIdsResult,
  IGetBusinessTripsTravelAndSubsistenceExpensesByIdsQuery,
  IUpdateBusinessTripTravelAndSubsistenceExpenseParams,
  IUpdateBusinessTripTravelAndSubsistenceExpenseResult,
  IUpdateBusinessTripTravelAndSubsistenceExpenseQuery,
  IInsertBusinessTripTravelAndSubsistenceExpenseParams,
  IInsertBusinessTripTravelAndSubsistenceExpenseResult,
  IInsertBusinessTripTravelAndSubsistenceExpenseQuery,
  IDeleteBusinessTripTravelAndSubsistenceExpenseParams,
  IDeleteBusinessTripTravelAndSubsistenceExpenseResult,
  IDeleteBusinessTripTravelAndSubsistenceExpenseQuery,
} from './__generated__/business-trips-expenses-travel-and-subsistence.types.js';
export type {
  IGetAllBusinessTripsOtherExpensesParams,
  IGetAllBusinessTripsOtherExpensesResult,
  IGetAllBusinessTripsOtherExpensesQuery,
  IGetBusinessTripsOtherExpensesByBusinessTripIdsParams,
  IGetBusinessTripsOtherExpensesByBusinessTripIdsResult,
  IGetBusinessTripsOtherExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsOtherExpensesByChargeIdsParams,
  IGetBusinessTripsOtherExpensesByChargeIdsResult,
  IGetBusinessTripsOtherExpensesByChargeIdsQuery,
  IGetBusinessTripsOtherExpensesByIdsParams,
  IGetBusinessTripsOtherExpensesByIdsResult,
  IGetBusinessTripsOtherExpensesByIdsQuery,
  IUpdateBusinessTripOtherExpenseParams,
  IUpdateBusinessTripOtherExpenseResult,
  IUpdateBusinessTripOtherExpenseQuery,
  IInsertBusinessTripOtherExpenseParams,
  IInsertBusinessTripOtherExpenseResult,
  IInsertBusinessTripOtherExpenseQuery,
  IDeleteBusinessTripOtherExpenseParams,
  IDeleteBusinessTripOtherExpenseResult,
  IDeleteBusinessTripOtherExpenseQuery,
} from './__generated__/business-trips-expenses-other.types.js';
export type {
  IUpdateBusinessTripEmployeePaymentParams,
  IUpdateBusinessTripEmployeePaymentResult,
  IUpdateBusinessTripEmployeePaymentQuery,
  IInsertBusinessTripEmployeePaymentParams,
  IInsertBusinessTripEmployeePaymentResult,
  IInsertBusinessTripEmployeePaymentQuery,
  IDeleteBusinessTripEmployeePaymentParams,
  IDeleteBusinessTripEmployeePaymentResult,
  IDeleteBusinessTripEmployeePaymentQuery,
  IReplaceBusinessTripsEmployeePaymentsChargeIdParams,
  IReplaceBusinessTripsEmployeePaymentsChargeIdResult,
  IReplaceBusinessTripsEmployeePaymentsChargeIdQuery,
  IGetBusinessTripEmployeePaymentsByChargeIdsParams,
  IGetBusinessTripEmployeePaymentsByChargeIdsResult,
  IGetBusinessTripEmployeePaymentsByChargeIdsQuery,
} from './__generated__/business-trips-employee-payments.types.js';
export type BusinessTripProto = Omit<IGetAllBusinessTripsResult, 'id' | 'name'> & {
  id: NonNullable<IGetAllBusinessTripsResult['id']>;
  name: NonNullable<IGetAllBusinessTripsResult['name']>;
};
