import type { IGetAllBusinessTripsResult } from './__generated__/business-trips.types.js';

export * from './__generated__/types.js';
export * from './__generated__/business-trips.types.js';
export type {
  IGetBusinessTripsAttendeesByBusinessTripIdsParams,
  IGetBusinessTripsAttendeesByBusinessTripIdsResult,
  IGetBusinessTripsAttendeesByBusinessTripIdsQuery,
  IAddBusinessTripAttendeesParams,
  IAddBusinessTripAttendeesResult,
  IAddBusinessTripAttendeesQuery,
  IUpdateBusinessTripAttendeeParams,
  IUpdateBusinessTripAttendeeResult,
  IUpdateBusinessTripAttendeeQuery,
  IRemoveBusinessTripAttendeesParams,
  IRemoveBusinessTripAttendeesResult,
  IRemoveBusinessTripAttendeesQuery,
  IGetLastFlightByDateAndAttendeeIdParams,
  IGetLastFlightByDateAndAttendeeIdResult,
  IGetLastFlightByDateAndAttendeeIdQuery,
  IGetBusinessTripsByAttendeeIdParams,
  IGetBusinessTripsByAttendeeIdResult,
  IGetBusinessTripsByAttendeeIdQuery,
} from './__generated__/business-trips-attendees.types.js';
export * from './__generated__/business-trips-tax-variables.types.js';
export type {
  business_trip_transaction_type,
  currency,
  IGetBusinessTripsExpensesByBusinessTripIdsParams,
  IGetBusinessTripsExpensesByBusinessTripIdsResult,
  IGetBusinessTripsExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsExpensesByIdsParams,
  IGetBusinessTripsExpensesByIdsResult,
  IGetBusinessTripsExpensesByIdsQuery,
  IGetUncategorizedTransactionsByBusinessTripIdParams,
  IGetUncategorizedTransactionsByBusinessTripIdResult,
  IGetUncategorizedTransactionsByBusinessTripIdQuery,
  IUpdateBusinessTripExpenseParams,
  IUpdateBusinessTripExpenseResult,
  IUpdateBusinessTripExpenseQuery,
  IInsertBusinessTripExpenseParams,
  IInsertBusinessTripExpenseResult,
  IInsertBusinessTripExpenseQuery,
  IDeleteBusinessTripExpenseParams,
  IDeleteBusinessTripExpenseResult,
  IDeleteBusinessTripExpenseQuery,
} from './__generated__/business-trips-expenses.types.js';
export type {
  IGetBusinessTripsExpenseMatchesByTransactionIdsParams,
  IGetBusinessTripsExpenseMatchesByTransactionIdsResult,
  IGetBusinessTripsExpenseMatchesByTransactionIdsQuery,
  IGetBusinessTripsExpenseMatchesByExpenseIdsParams,
  IGetBusinessTripsExpenseMatchesByExpenseIdsResult,
  IGetBusinessTripsExpenseMatchesByExpenseIdsQuery,
  IInsertBusinessTripExpenseMatchParams,
  IInsertBusinessTripExpenseMatchResult,
  IInsertBusinessTripExpenseMatchQuery,
  IDeleteBusinessTripExpenseMatchParams,
  IDeleteBusinessTripExpenseMatchResult,
  IDeleteBusinessTripExpenseMatchQuery,
  IDeleteSpecificBusinessTripExpenseMatchParams,
  IDeleteSpecificBusinessTripExpenseMatchResult,
  IDeleteSpecificBusinessTripExpenseMatchQuery,
} from './__generated__/business-trips-expenses-transactions-match.types.js';
export type {
  flight_class,
  IGetBusinessTripsFlightsExpensesByBusinessTripIdsParams,
  IGetBusinessTripsFlightsExpensesByBusinessTripIdsResult,
  IGetBusinessTripsFlightsExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsFlightsExpensesByIdsParams,
  IGetBusinessTripsFlightsExpensesByIdsResult,
  IGetBusinessTripsFlightsExpensesByIdsQuery,
  IUpdateBusinessTripFlightsExpenseParams,
  IUpdateBusinessTripFlightsExpenseResult,
  IUpdateBusinessTripFlightsExpenseQuery,
  IInsertBusinessTripFlightsExpenseParams,
  IInsertBusinessTripFlightsExpenseResult,
  IInsertBusinessTripFlightsExpenseQuery,
  IDeleteBusinessTripFlightsExpenseParams,
  IDeleteBusinessTripFlightsExpenseResult,
  IDeleteBusinessTripFlightsExpenseQuery,
} from './__generated__/business-trips-expenses-flights.types.js';
export type {
  IGetBusinessTripsAccommodationsExpensesByBusinessTripIdsParams,
  IGetBusinessTripsAccommodationsExpensesByBusinessTripIdsResult,
  IGetBusinessTripsAccommodationsExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsAccommodationsExpensesByIdsParams,
  IGetBusinessTripsAccommodationsExpensesByIdsResult,
  IGetBusinessTripsAccommodationsExpensesByIdsQuery,
  IUpdateBusinessTripAccommodationsExpenseParams,
  IUpdateBusinessTripAccommodationsExpenseResult,
  IUpdateBusinessTripAccommodationsExpenseQuery,
  IInsertBusinessTripAccommodationsExpenseParams,
  IInsertBusinessTripAccommodationsExpenseResult,
  IInsertBusinessTripAccommodationsExpenseQuery,
  IDeleteBusinessTripAccommodationsExpenseParams,
  IDeleteBusinessTripAccommodationsExpenseResult,
  IDeleteBusinessTripAccommodationsExpenseQuery,
} from './__generated__/business-trips-expenses-accommodations.types.js';
export type {
  IGetBusinessTripsTravelAndSubsistenceExpensesByBusinessTripIdsParams,
  IGetBusinessTripsTravelAndSubsistenceExpensesByBusinessTripIdsResult,
  IGetBusinessTripsTravelAndSubsistenceExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsTravelAndSubsistenceExpensesByIdsParams,
  IGetBusinessTripsTravelAndSubsistenceExpensesByIdsResult,
  IGetBusinessTripsTravelAndSubsistenceExpensesByIdsQuery,
  IUpdateBusinessTripTravelAndSubsistenceExpenseParams,
  IUpdateBusinessTripTravelAndSubsistenceExpenseResult,
  IUpdateBusinessTripTravelAndSubsistenceExpenseQuery,
  IInsertBusinessTripTravelAndSubsistenceExpenseParams,
  IInsertBusinessTripTravelAndSubsistenceExpenseResult,
  IInsertBusinessTripTravelAndSubsistenceExpenseQuery,
  IDeleteBusinessTripTravelAndSubsistenceExpenseParams,
  IDeleteBusinessTripTravelAndSubsistenceExpenseResult,
  IDeleteBusinessTripTravelAndSubsistenceExpenseQuery,
} from './__generated__/business-trips-expenses-travel-and-subsistence.types.js';
export type {
  IGetBusinessTripsOtherExpensesByBusinessTripIdsParams,
  IGetBusinessTripsOtherExpensesByBusinessTripIdsResult,
  IGetBusinessTripsOtherExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsOtherExpensesByIdsParams,
  IGetBusinessTripsOtherExpensesByIdsResult,
  IGetBusinessTripsOtherExpensesByIdsQuery,
  IUpdateBusinessTripOtherExpenseParams,
  IUpdateBusinessTripOtherExpenseResult,
  IUpdateBusinessTripOtherExpenseQuery,
  IInsertBusinessTripOtherExpenseParams,
  IInsertBusinessTripOtherExpenseResult,
  IInsertBusinessTripOtherExpenseQuery,
  IDeleteBusinessTripOtherExpenseParams,
  IDeleteBusinessTripOtherExpenseResult,
  IDeleteBusinessTripOtherExpenseQuery,
} from './__generated__/business-trips-expenses-other.types.js';
export type {
  IUpdateBusinessTripEmployeePaymentParams,
  IUpdateBusinessTripEmployeePaymentResult,
  IUpdateBusinessTripEmployeePaymentQuery,
  IInsertBusinessTripEmployeePaymentParams,
  IInsertBusinessTripEmployeePaymentResult,
  IInsertBusinessTripEmployeePaymentQuery,
  IDeleteBusinessTripEmployeePaymentParams,
  IDeleteBusinessTripEmployeePaymentResult,
  IDeleteBusinessTripEmployeePaymentQuery,
  IReplaceBusinessTripsEmployeePaymentsChargeIdParams,
  IReplaceBusinessTripsEmployeePaymentsChargeIdResult,
  IReplaceBusinessTripsEmployeePaymentsChargeIdQuery,
  IGetBusinessTripEmployeePaymentsByChargeIdsParams,
  IGetBusinessTripEmployeePaymentsByChargeIdsResult,
  IGetBusinessTripEmployeePaymentsByChargeIdsQuery,
  IGetBusinessTripEmployeePaymentByIdParams,
  IGetBusinessTripEmployeePaymentByIdResult,
  IGetBusinessTripEmployeePaymentByIdQuery,
} from './__generated__/business-trips-employee-payments.types.js';
export type {
  IGetBusinessTripsCarRentalExpensesByBusinessTripIdsParams,
  IGetBusinessTripsCarRentalExpensesByBusinessTripIdsResult,
  IGetBusinessTripsCarRentalExpensesByBusinessTripIdsQuery,
  IGetBusinessTripsCarRentalExpensesByIdsParams,
  IGetBusinessTripsCarRentalExpensesByIdsResult,
  IGetBusinessTripsCarRentalExpensesByIdsQuery,
  IUpdateBusinessTripCarRentalExpenseParams,
  IUpdateBusinessTripCarRentalExpenseResult,
  IUpdateBusinessTripCarRentalExpenseQuery,
  IInsertBusinessTripCarRentalExpenseParams,
  IInsertBusinessTripCarRentalExpenseResult,
  IInsertBusinessTripCarRentalExpenseQuery,
  IDeleteBusinessTripCarRentalExpenseParams,
  IDeleteBusinessTripCarRentalExpenseResult,
  IDeleteBusinessTripCarRentalExpenseQuery,
} from './__generated__/business-trips-expenses-car-rental.types.js';
export type BusinessTripProto = Omit<IGetAllBusinessTripsResult, 'id' | 'name'> & {
  id: NonNullable<IGetAllBusinessTripsResult['id']>;
  name: NonNullable<IGetAllBusinessTripsResult['name']>;
};
