export function cleanField(raw: string, trimZeros = false): string {
  const trimmed = raw.trim();
  const firstChar = trimmed[0];
  if (firstChar === ' ') {
    return '';
  }
  if (firstChar === '0' && trimZeros) {
    let extraTrimmed = trimmed;
    while (extraTrimmed[0] === '0') {
      extraTrimmed = extraTrimmed.slice(1);
    }
    return extraTrimmed;
  }
  return trimmed;
}

export const accountsDict: Map<string, string[]> = new Map<string, string[]>([
  ['Abaca', ['נסעחול2']],
  ['Accounting', ['הנחש']],
  ['ActiveCampaign, LLC', []],
  ['Ahrefs Pte. Ltd.', ['Ahrefs']],
  ['Air France', ['AIR']],
  ['AirBnB', ['AIRBNB']],
  ['Alcatraz Cruises', ['נסעחול2']],
  ['Altinity Inc', ['Vercel Inc.']],
  ['Amazon Web Services EMEA SARL', ['AWS']],
  ['Amazon.com', ['Amazon.com']],
  ['AMERICAN001243278088/FORT WORTH', ['נסעחול2']],
  ['Arda Tanrikulu', ['Arda Tanrikulu']],
  ['Autogrill - Somma Lombardo', ["AUTOGRILL"]],
  ['Avi Peretz', ['Avi Peretz']],
  ['Better Uptime (HODL llc)', ["BETTER"]],
  ['Business Insurance', ['ביטוח עסק']],
  ['Business Trip', ['נסעחול1', 'נסעחול2', 'נסעחול3', 'נסעחול4', 'נסעחול5']],
  ['Business Trip 1', ['נסעחול1']],
  ['Business Trip 2', ['נסעחול2']],
  ['Business Trip 3', ['נסעחול3']],
  ['Business Trip 4', ['נסעחול4']],
  ['Business Trip 5', ['נסעחול5']],
  ['Cal.com, Inc.', ['CAL']],
  ['Calendly LLC', ['Calendly LLC']],
  ['CITY LIFE HOTEL POLIZIANO', ["CITYLIFE"]],
  ['ClickHouse, Inc.', ['CLICKHOUSE']],
  ['Cloudflare, Inc.', ['Cloudflare, Inc']],
  ['Compensation fund expenses', ['הוצגמל']],
  ['Consultancy', ['יעוץ']],
  ['Cooper Press Ltd', ["COOPERPRE"]],
  ['Crisp IM SARL', ['Crisp IM SARL']],
  ['Dalet Digital Media Systems USA Inc', ['Dalet Digital M']],
  ['Deel Germany GmbH', ['Deel Germany Gm']],
  ['Deliveroo', ['DeliverR']],
  ['denelop o.d.', ['Denelop']],
  ['Development', ['פיתוח']],
  ['Development Israel', ['פיתוחארץ']],
  ['DHL (Israel) LTD', ['DHL (Israel) LT']],
  ['Dividend', ['Dividend']],
  ['Dividend Tax Deduction Origin', ['ניבמדיב']],
  ['Dividend Withholding Tax', ['ניבמדיב']],
  ['Dotan Dividend', ['Dotan Dividend']],
  ['Dotan Employee', ['DotanEm']],
  ['EIRL Charly Poly Engineering EIRL', ['EIRL Charly Pol']],
  ['Exchange Rates', ['שער']],
  ['Fee', ['עמל']],
  ['Gett', ['נסע']],
  ['Gifts', ["מתנות"]],
  ['Gil Employee', ['GilEm']],
  ['Gilad Employee', ['GiladEm']],
  ['GitHub, Inc', ['GitHub']],
  ['GoDaddy.com, LLC', ['GoDaddy']],
  ['Google Cloud EMEA Limited', ['Google Ireland']],
  ['Gornitzky & Co., Advocates', ['Gornitzky & Co.']],
  ['Green Invoice', ['Green Invoice']],
  ['Hasura, Inc.', ["Hashura"]],
  ['Heroku', ['Heroku']],
  ['Hilton Lake Como', ["HILTON LAKE"]],
  ['Idan Am-Shalem', ['Idan Am-Shalem']],
  ['Income no VAT', ['הכנפט']],
  ['Income with VAT', ["הכנ"]],
  ['Isracard', ['כא1074', 'כא1082']], // TODO: duplication between "Isracard" and the cards as individuals
  ['Jelly JS Kamil Kisiela', ['Jelly JS Kamil']],
  ['Krudo, Como', ["KRUDO"]],
  ['L\'Antica Trattoria', ["ANTICA"]],
  ['Lance Global Inc', ['Lance Global In']],
  ['LaunchMade Web Services', ['LaunchMade Web']],
  ['Le Coq', ["Rest"]],
  ['Legal', ['משפט']],
  ['Les Éditeurs', ['LesE']],
  ['Luisa\'s Restaurant Wine Bar', ['נסעחול2']],
  ['Maintenance', ['אחזקה']],
  ['Marketing', ["פרסום"]],
  ['Marks and Spencer PLC', ['Marks and Spenc']],
  ['Meetup', ['Meetup']],
  ['Michael Chan', ['Michael Chan']],
  ['Microsoft Azure', ['Microsoft Azure']],
  ['MUSIC STORE professional GmbH', ["PaypalM"]],
  ['NAME COM', ["Name.com"]],
  ['New Thai Elephant', ['נסעחול2']],
  ['Notion Labs, Inc', ['Notion Labs, In']],
  ['Office', ['משרד']],
  ['Outreach Corporation', ['Outreach Corpor']],
  ['Paddle.com Security Checks', ["Paddle Net"]],
  ['Pat\'s Cafe', ['נסעחול2']],
  ['Payper', ['Payper']],
  ['Pension expenses', ['הוצגמל']],
  ['Piccolo Forno', ['נסעחול2']],
  ['Poalim', ['עמל']],
  ['Pulumi Corporation', ['Pulumi Comporat']],
  ['Raintank Inc dba Grafana Labs', ['Raintank Inc db']],
  ['Raveh Ravid & Co', ['Raveh Ravid & C']],
  ['Render', ['Render']],
  ['Rent', ['שכר דירה']],
  ['Retool Inc', ['Retool']],
  ['Ristorante PANE e TULIPANI con Pizzeria', ["TULIPANI"]],
  ['Saihajpreet Singh', ['Saihajpreet Sin']],
  ['Salary expenses', ['שכע']],
  ['Sentry', ['Sentry']],
  ['Slack Technologies Limited', ['Slack']],
  ['SLAVA UKRAINI', ['Slava Ukraini']],
  ['Social Security Deductions', ['בלני']],
  ['Social security expenses', ['בלני']],
  ['Surisan', ['נסעחול2']],
  ['Swift Fee', ['עמל']],
  ['Tamal', ['Tamal']],
  ['Tartine Manufactory', ['נסעחול2']],
  ['Tax', ['מקדמות2022', 'מקדמותעח', 'מקדמה לשלם 21', 'קנס מס הכנסה']], // TODO: multiple tax accounts
  ['Tax Deductions', ['מהני']],
  ['Taxi Milano', ["TAXI"]],
  ['Thaï Basilic Rosa Parks', ['Basilic']],
  ['The Graph Foundation', ['The Graph Found']],
  ['The Linux Foundation', ['Linux Foundatio']],
  ['The Red Jack Saloon', ['נסעחול2']],
  ['TourBeaver.com', ['נסעחול2']],
  ['Training fund expenses', ['הוצקהל']],
  ['tshirtmart', ["Tshirt Wholesa"]],
  ['Tuval Employee', ['TuvalEm']],
  ['Uber', ['Uber']],
  ['United Airlines', ["United"]],
  ['Uri Dividend', ['Uri Dividend']],
  ['Uri Employee', ['UriEm']],
  ['VAT', ['מעמחוז', 'ריביתמעמ', 'תשו']], // TODO: multiple tax accounts + duplication with מעמ
  ['Vercel Inc.', ['Vercel Inc.']],
  ['Website', ['אתר']],
  ['Y.T AMIRIM DISTRIBUTION LTD', ['Y.T.Amirim']],
  ['Yahel Mor', ['Yahel Mor']],
  ['Yassin Eldeeb', ['YASSIN']],
  ['Yossi Yaron', []],
  ['Zkufot expenses', ['הוצז']],
  ['Zkufot income', ['זקופות']],
  ['אחזקת מחשב', ['אחזקת מחשב']],
  ['איילון פנסיה', ['איילוןפ']],
  ['ביקורת', ['ביקורת']],
  ['דטה פרינט בעמ', ['דטה פרינט בעמ']],
  ['דמי חבר', ['דמי חבר']],
  ['הפניקס חברה לביטוח בע"מ', ['הפניקס']],
  ['כא1074', ['כא1074']],
  ['כא1082', ['כא1082']],
  ['כא5972', ['כא5972']],
  ['מגדל השתלמות', ['מגדלהש']],
  ['מגדל פנסיה', ['מגדלפנ']],
  ['מחשבים', ['מחשבים']],
  ['מנורה פנסיה', ['מנורהפנ']],
  ['מעמ', ['מעמחוז', 'תשו']],
  ['משלוחים', ['משלוחים']],
  ['עוש', ['עוש']],
  ['עוש1', ['עוש1']],
  ['עוש2', ['עוש2']],
  ['עוש3', ['עוש3']],
  ['פונגו פונגו', ["Pongo"]],
  ['פיוז אוטוטק בעמ', ["פיוז אוטוטק בעמ"]],
  ['פניקס השתלמות', ['פניקסהש']],
  ['פניקס\\אקסלנס השתלמות', ['פניקסהש']],
  ['קריפטו1', ['קריפטו1']],
  ['קריפטו2', []],
  ['קריפטו3', []],
  ['קריפטו4', []],
  ['קריפטו5', []],
]);

export function checkAccountsMatch(
  movementAccount: string,
  ledgerAccount?: string | null,
): boolean {
  if (!ledgerAccount) {
    return false;
  }

  const options = accountsDict.get(ledgerAccount);
  if (!options) {
    return false;
  }
  if (options.includes(movementAccount)) {
    return true;
  }
  return false;
}
