/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthBusinessesImport } from './routes/_auth/businesses'
import { Route as AuthChargesIndexImport } from './routes/_auth/charges/index'
import { Route as AuthChargesIdImport } from './routes/_auth/charges/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthBusinessesRoute = AuthBusinessesImport.update({
  path: '/businesses',
  getParentRoute: () => AuthRoute,
} as any)

const AuthChargesIndexRoute = AuthChargesIndexImport.update({
  path: '/charges/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthChargesIdRoute = AuthChargesIdImport.update({
  path: '/charges/$id',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/businesses': {
      id: '/_auth/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof AuthBusinessesImport
      parentRoute: typeof AuthImport
    }
    '/_auth/charges/$id': {
      id: '/_auth/charges/$id'
      path: '/charges/$id'
      fullPath: '/charges/$id'
      preLoaderRoute: typeof AuthChargesIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/charges/': {
      id: '/_auth/charges/'
      path: '/charges'
      fullPath: '/charges'
      preLoaderRoute: typeof AuthChargesIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthRoute: AuthRoute.addChildren({
    AuthBusinessesRoute,
    AuthChargesIdRoute,
    AuthChargesIndexRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/businesses",
        "/_auth/charges/$id",
        "/_auth/charges/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/businesses": {
      "filePath": "_auth/businesses.tsx",
      "parent": "/_auth"
    },
    "/_auth/charges/$id": {
      "filePath": "_auth/charges/$id.tsx",
      "parent": "/_auth"
    },
    "/_auth/charges/": {
      "filePath": "_auth/charges/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
