version: '1.0'
name: 'accounter-dev'
services:
  db:
    image: postgres:16-alpine
    networks:
      - 'stack'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounter
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./.accounter-dev/postgresql/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

networks:
  stack: {}
