sources:
  - name: GreenInvoice
    handler:
      jsonSchema:
        endpoint: 'https://api.greeninvoice.co.il/api/v1'
        operationHeaders:
          Authorization: Bearer {context.authToken}
          Content-Type: application/json
        operations:
          - type: Mutation
            field: addExpense
            path: /expenses
            method: POST
            requestSchema: ../json-schemas/greenInvoice.json#/definitions/addExpenseRequest
            responseSchema: ../json-schemas/greenInvoice.json#/definitions/addExpenseResponse

          - type: Mutation
            field: addDocument
            path: /documents
            method: POST
            requestSchema: ../json-schemas/greenInvoice.json#/definitions/addDocumentRequest
            responseSchema: ../json-schemas/greenInvoice.json#/definitions/addDocumentResponse

          - type: Query
            field: previewDocument
            path: /documents/preview
            method: POST
            requestSchema: ../json-schemas/greenInvoice.json#/definitions/previewDocumentRequest
            responseSchema: ../json-schemas/greenInvoice.json#/definitions/previewDocumentResponse

          - type: Query
            field: getExpense
            path: /expenses/{args.id}
            method: GET
            argTypeMap:
              id:
                type: string
                nullable: false
            responseSchema: ../json-schemas/greenInvoice.json#/definitions/getExpenseResponse

          - type: Mutation
            field: updateExpense
            path: /expenses/{args.id}
            method: PUT
            requestSchema: ../json-schemas/greenInvoice.json#/definitions/updateExpenseRequest
            responseSchema: ../json-schemas/greenInvoice.json#/definitions/updateExpenseResponse

          - type: Query
            field: searchExpenses
            path: /expenses/search
            method: POST
            requestSchema: ../json-schemas/greenInvoice.json#/definitions/searchExpensesRequest
            responseSchema: ../json-schemas/greenInvoice.json#/definitions/searchExpensesResponse

          - type: Query
            field: searchDocuments
            path: /documents/search
            method: POST
            requestSchema: ../json-schemas/greenInvoice.json#/definitions/searchDocumentsRequest
            responseSchema: ../json-schemas/greenInvoice.json#/definitions/searchDocumentsResponse

          - type: Mutation
            field: addExpenseDraftByFile
            path: /expenses/file
            method: POST
            requestSchema: ../json-schemas/greenInvoice.json#/definitions/addExpenseDraftByFileRequest
            responseByStatusCode:
              200:
                responseSchema: ../json-schemas/greenInvoice.json#/definitions/addExpenseDraftByFileResponse
              201:
                responseSchema: ../json-schemas/greenInvoice.json#/definitions/addExpenseDraftByFileResponse
              400:
                responseSchema: ../json-schemas/greenInvoice.json#/definitions/generalErrorResponse
              404:
                responseSchema: ../json-schemas/greenInvoice.json#/definitions/generalErrorResponse
              405:
                responseSchema: ../json-schemas/greenInvoice.json#/definitions/generalErrorResponse

          - type: Query
            field: searchExpenseDrafts
            path: /expenses/drafts/search
            method: POST
            requestSchema: ../json-schemas/greenInvoice.json#/definitions/searchExpenseDraftsRequest
            responseByStatusCode:
              200:
                responseSchema: ../json-schemas/greenInvoice.json#/definitions/searchExpenseDraftsResponse
              201:
                responseSchema: ../json-schemas/greenInvoice.json#/definitions/searchExpenseDraftsResponse
              404:
                responseSchema: ../json-schemas/greenInvoice.json#/definitions/generalErrorResponse

  - name: GreenInvoiceNew
    handler:
      jsonSchema:
        endpoint: 'https://apigw.greeninvoice.co.il'
        operationHeaders:
          Authorization: Bearer {context.authToken}
          Content-Type: application/json
        operations:
          - type: Query
            field: getFileUploadUrl
            path: /file-upload/v1/url
            method: GET
            argTypeMap:
              context:
                type: string
              data:
                type: object
                properties:
                  source:
                    type: integer
                  id:
                    type: string
                  state:
                    type: string
                required:
                  - source
            queryStringOptions:
              jsonStringify: true
            queryParamArgMap:
              context: context
              data: data
            responseSchema: ../json-schemas/greenInvoice.json#/definitions/getFileUploadUrlResponse

          - type: Query
            field: getBankTransactions
            path: /open-banking/v2/transactions
            method: GET
            argTypeMap:
              valueDate:
                type: object
                properties:
                  from:
                    type: string
                  to:
                    type: string
                required:
                  - from
                  - to
              from:
                type: number
              size:
                type: number
              bookingStatus:
                type: string
            queryStringOptions:
              indices: true
              arrayFormat: brackets
            queryParamArgMap:
              valueDate: valueDate
              from: from
              size: size
              bookingStatus: bookingStatus
            responseSchema: ../json-schemas/greenInvoice.json#/definitions/getBankTransactionsResponse
codegen:
  ignoreEnumValuesFromSchema: false

serve:
  browser: false

sdk:
  generateOperations:
    selectionSetDepth: 5
