/**
 * Charge factory for test fixtures
 *
 * Creates minimal charge objects ready for database insertion.
 *
 * Based on charges table schema from migrations and charges.provider.ts:
 * - Required: owner_id
 * - Optional: type, accountant_status, user_description, tax_category_id, optional_vat, documents_optional_flag
 *
 * @see packages/server/src/modules/charges/providers/charges.provider.ts (generateCharge query)
 * @see packages/migrations/src/actions/*-charges-*.ts (migrations)
 */

import { makeUUID } from './ids.js';

/**
 * Charge insert parameters shape
 *
 * Matches the fields from generateCharge SQL query in charges.provider.ts:
 * INSERT INTO accounter_schema.charges (owner_id, type, accountant_status, user_description, tax_category_id, optional_vat, documents_optional_flag)
 */
export interface ChargeInsertParams {
  id?: string;
  owner_id: string;
  type?: string | null;
  accountant_status?: string | null;
  user_description?: string | null;
  tax_category_id?: string | null;
  optional_vat?: boolean | null;
  documents_optional_flag?: boolean | null;
}

/**
 * Create a charge for test fixtures
 *
 * @param params - Required fields (owner_id, tax_category_id) and optional user_description
 * @param overrides - Optional overrides for any charge field
 * @returns Charge object ready for database insertion
 *
 * @remarks
 * - owner_id is required (must be a valid business UUID)
 * - tax_category_id defaults to deterministic UUID if not provided
 * - user_description defaults to null (will be auto-generated by database if needed)
 * - type defaults to null (database will determine based on related records)
 * - accountant_status defaults to null
 * - optional_vat defaults to null (uses tax category default)
 * - documents_optional_flag defaults to null (uses business default)
 * - id defaults to deterministic UUID if not provided
 *
 * @example
 * ```typescript
 * // Minimal charge with required fields
 * const charge = createCharge({
 *   owner_id: makeUUID('test-owner'),
 *   tax_category_id: makeUUID('tax-cat-1'),
 * });
 *
 * // Charge with user description
 * const descCharge = createCharge(
 *   {
 *     owner_id: makeUUID('test-owner'),
 *     tax_category_id: makeUUID('tax-cat-1'),
 *     user_description: 'Office supplies purchase',
 *   }
 * );
 *
 * // Charge with overrides
 * const customCharge = createCharge(
 *   {
 *     owner_id: makeUUID('test-owner'),
 *     tax_category_id: makeUUID('tax-cat-1'),
 *   },
 *   {
 *     type: 'PAYROLL',
 *     accountant_status: 'REVIEWED',
 *     optional_vat: true,
 *   }
 * );
 * ```
 */
export function createCharge(
  params: {
    owner_id: string;
    tax_category_id?: string;
    user_description?: string;
  },
  overrides?: Partial<ChargeInsertParams>,
): ChargeInsertParams {
  return {
    id: makeUUID(),
    owner_id: params.owner_id,
    type: null,
    accountant_status: null,
    user_description: params.user_description ?? null,
    tax_category_id: params.tax_category_id ?? makeUUID('default-tax-category'),
    optional_vat: null,
    documents_optional_flag: null,
    ...overrides,
  };
}
