on:
  workflow_call:
    secrets:
      hiveToken:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: accounter-fullstack
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 2

      - name: schema publish
        env:
          HIVE_TOKEN: ${{ secrets.hiveToken }}
        run: |
          curl -sSL https://graphql-hive.com/install.sh | sh
          hive schema:publish "packages/server/src/modules/*/typeDefs/*.graphql.ts" --github
