on:
  workflow_call:
    secrets:
      hiveRegistryToken:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: accounter-fullstack
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: schema publish
        env:
          HIVE_REGISTRY_TOKEN: ${{ secrets.hiveRegistryToken }}
        run: |
          curl -sSL https://graphql-hive.com/install.sh | sh
          hive schema:publish "packages/server/src/modules/*/typeDefs/*.graphql.ts" --github
