on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 2

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          localDB: 'false'
          codegen: 'false'
          pgTyped: 'false'

      - name: Lint ESLint
        run: yarn lint
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Lint Prettier
        run: yarn prettier:check
