name: Require Changeset

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - 'packages/**'
    branches:
      - main

jobs:
  check-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Check for changeset file
        run: |
          git fetch origin ${{ github.base_ref }}
          # Find changeset files added or modified in this PR
          if ! git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q '^\.changeset\/.*\.md$'; then
            echo "::error ::No changeset found. Please add a changeset using 'yarn changeset' or 'npx changeset' before merging this pull request."
            exit 1
          fi
